/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressTag
 */
export interface AddressTag {
    /**
     * 
     * @type {string}
     * @memberof AddressTag
     */
    addressHash: string;
    /**
     * 
     * @type {string}
     * @memberof AddressTag
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof AddressTag
     */
    label: string;
}

/**
 * Check if a given object implements the AddressTag interface.
 */
export function instanceOfAddressTag(value: object): boolean {
    if (!('addressHash' in value)) return false;
    if (!('displayName' in value)) return false;
    if (!('label' in value)) return false;
    return true;
}

export function AddressTagFromJSON(json: any): AddressTag {
    return AddressTagFromJSONTyped(json, false);
}

export function AddressTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressTag {
    if (json == null) {
        return json;
    }
    return {
        
        'addressHash': json['address_hash'],
        'displayName': json['display_name'],
        'label': json['label'],
    };
}

export function AddressTagToJSON(value?: AddressTag | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address_hash': value['addressHash'],
        'display_name': value['displayName'],
        'label': value['label'],
    };
}

