/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressTag } from './AddressTag';
import {
    AddressTagFromJSON,
    AddressTagFromJSONTyped,
    AddressTagToJSON,
} from './AddressTag';
import type { TokenInfo } from './TokenInfo';
import {
    TokenInfoFromJSON,
    TokenInfoFromJSONTyped,
    TokenInfoToJSON,
} from './TokenInfo';
import type { WatchlistName } from './WatchlistName';
import {
    WatchlistNameFromJSON,
    WatchlistNameFromJSONTyped,
    WatchlistNameToJSON,
} from './WatchlistName';

/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    creatorAddressHash?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    creationTxHash?: string;
    /**
     * 
     * @type {TokenInfo}
     * @memberof Address
     */
    token?: TokenInfo;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    coinBalance?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    exchangeRate?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    implementationAddress?: string;
    /**
     * 
     * @type {number}
     * @memberof Address
     */
    blockNumberBalanceUpdatedAt?: number;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    hash: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    implementationName?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    isContract?: boolean;
    /**
     * 
     * @type {Array<AddressTag>}
     * @memberof Address
     */
    privateTags?: Array<AddressTag>;
    /**
     * 
     * @type {Array<WatchlistName>}
     * @memberof Address
     */
    watchlistNames?: Array<WatchlistName>;
    /**
     * 
     * @type {Array<AddressTag>}
     * @memberof Address
     */
    publicTags?: Array<AddressTag>;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    isVerified?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    hasBeaconChainWithdrawals?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    hasCustomMethodsRead?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    hasCustomMethodsWrite?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    hasDecompiledCode?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    hasLogs?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    hasMethodsRead?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    hasMethodsWrite?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    hasMethodsReadProxy?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    hasMethodsWriteProxy?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    hasTokenTransfers?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    hasTokens?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    hasValidatedBlocks?: boolean;
}

/**
 * Check if a given object implements the Address interface.
 */
export function instanceOfAddress(value: object): boolean {
    if (!('hash' in value)) return false;
    return true;
}

export function AddressFromJSON(json: any): Address {
    return AddressFromJSONTyped(json, false);
}

export function AddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): Address {
    if (json == null) {
        return json;
    }
    return {
        
        'creatorAddressHash': json['creator_address_hash'] == null ? undefined : json['creator_address_hash'],
        'creationTxHash': json['creation_tx_hash'] == null ? undefined : json['creation_tx_hash'],
        'token': json['token'] == null ? undefined : TokenInfoFromJSON(json['token']),
        'coinBalance': json['coin_balance'] == null ? undefined : json['coin_balance'],
        'exchangeRate': json['exchange_rate'] == null ? undefined : json['exchange_rate'],
        'implementationAddress': json['implementation_address'] == null ? undefined : json['implementation_address'],
        'blockNumberBalanceUpdatedAt': json['block_number_balance_updated_at'] == null ? undefined : json['block_number_balance_updated_at'],
        'hash': json['hash'],
        'implementationName': json['implementation_name'] == null ? undefined : json['implementation_name'],
        'name': json['name'] == null ? undefined : json['name'],
        'isContract': json['is_contract'] == null ? undefined : json['is_contract'],
        'privateTags': json['private_tags'] == null ? undefined : ((json['private_tags'] as Array<any>).map(AddressTagFromJSON)),
        'watchlistNames': json['watchlist_names'] == null ? undefined : ((json['watchlist_names'] as Array<any>).map(WatchlistNameFromJSON)),
        'publicTags': json['public_tags'] == null ? undefined : ((json['public_tags'] as Array<any>).map(AddressTagFromJSON)),
        'isVerified': json['is_verified'] == null ? undefined : json['is_verified'],
        'hasBeaconChainWithdrawals': json['has_beacon_chain_withdrawals'] == null ? undefined : json['has_beacon_chain_withdrawals'],
        'hasCustomMethodsRead': json['has_custom_methods_read'] == null ? undefined : json['has_custom_methods_read'],
        'hasCustomMethodsWrite': json['has_custom_methods_write'] == null ? undefined : json['has_custom_methods_write'],
        'hasDecompiledCode': json['has_decompiled_code'] == null ? undefined : json['has_decompiled_code'],
        'hasLogs': json['has_logs'] == null ? undefined : json['has_logs'],
        'hasMethodsRead': json['has_methods_read'] == null ? undefined : json['has_methods_read'],
        'hasMethodsWrite': json['has_methods_write'] == null ? undefined : json['has_methods_write'],
        'hasMethodsReadProxy': json['has_methods_read_proxy'] == null ? undefined : json['has_methods_read_proxy'],
        'hasMethodsWriteProxy': json['has_methods_write_proxy'] == null ? undefined : json['has_methods_write_proxy'],
        'hasTokenTransfers': json['has_token_transfers'] == null ? undefined : json['has_token_transfers'],
        'hasTokens': json['has_tokens'] == null ? undefined : json['has_tokens'],
        'hasValidatedBlocks': json['has_validated_blocks'] == null ? undefined : json['has_validated_blocks'],
    };
}

export function AddressToJSON(value?: Address | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'creator_address_hash': value['creatorAddressHash'],
        'creation_tx_hash': value['creationTxHash'],
        'token': TokenInfoToJSON(value['token']),
        'coin_balance': value['coinBalance'],
        'exchange_rate': value['exchangeRate'],
        'implementation_address': value['implementationAddress'],
        'block_number_balance_updated_at': value['blockNumberBalanceUpdatedAt'],
        'hash': value['hash'],
        'implementation_name': value['implementationName'],
        'name': value['name'],
        'is_contract': value['isContract'],
        'private_tags': value['privateTags'] == null ? undefined : ((value['privateTags'] as Array<any>).map(AddressTagToJSON)),
        'watchlist_names': value['watchlistNames'] == null ? undefined : ((value['watchlistNames'] as Array<any>).map(WatchlistNameToJSON)),
        'public_tags': value['publicTags'] == null ? undefined : ((value['publicTags'] as Array<any>).map(AddressTagToJSON)),
        'is_verified': value['isVerified'],
        'has_beacon_chain_withdrawals': value['hasBeaconChainWithdrawals'],
        'has_custom_methods_read': value['hasCustomMethodsRead'],
        'has_custom_methods_write': value['hasCustomMethodsWrite'],
        'has_decompiled_code': value['hasDecompiledCode'],
        'has_logs': value['hasLogs'],
        'has_methods_read': value['hasMethodsRead'],
        'has_methods_write': value['hasMethodsWrite'],
        'has_methods_read_proxy': value['hasMethodsReadProxy'],
        'has_methods_write_proxy': value['hasMethodsWriteProxy'],
        'has_token_transfers': value['hasTokenTransfers'],
        'has_tokens': value['hasTokens'],
        'has_validated_blocks': value['hasValidatedBlocks'],
    };
}

