/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressCounters
 */
export interface AddressCounters {
    /**
     * 
     * @type {string}
     * @memberof AddressCounters
     */
    transactionsCount: string;
    /**
     * 
     * @type {string}
     * @memberof AddressCounters
     */
    tokenTransfersCount: string;
    /**
     * 
     * @type {string}
     * @memberof AddressCounters
     */
    gasUsageCount: string;
    /**
     * 
     * @type {string}
     * @memberof AddressCounters
     */
    validationsCount: string;
}

/**
 * Check if a given object implements the AddressCounters interface.
 */
export function instanceOfAddressCounters(value: object): boolean {
    if (!('transactionsCount' in value)) return false;
    if (!('tokenTransfersCount' in value)) return false;
    if (!('gasUsageCount' in value)) return false;
    if (!('validationsCount' in value)) return false;
    return true;
}

export function AddressCountersFromJSON(json: any): AddressCounters {
    return AddressCountersFromJSONTyped(json, false);
}

export function AddressCountersFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressCounters {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionsCount': json['transactions_count'],
        'tokenTransfersCount': json['token_transfers_count'],
        'gasUsageCount': json['gas_usage_count'],
        'validationsCount': json['validations_count'],
    };
}

export function AddressCountersToJSON(value?: AddressCounters | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'transactions_count': value['transactionsCount'],
        'token_transfers_count': value['tokenTransfersCount'],
        'gas_usage_count': value['gasUsageCount'],
        'validations_count': value['validationsCount'],
    };
}

