/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Argument
 */
export interface Argument {
    /**
     * 
     * @type {string}
     * @memberof Argument
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Argument
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof Argument
     */
    value?: string;
}

/**
 * Check if a given object implements the Argument interface.
 */
export function instanceOfArgument(value: object): boolean {
    return true;
}

export function ArgumentFromJSON(json: any): Argument {
    return ArgumentFromJSONTyped(json, false);
}

export function ArgumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Argument {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function ArgumentToJSON(value?: Argument | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'type': value['type'],
        'value': value['value'],
    };
}

