/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoinBalanceHistoryEntry
 */
export interface CoinBalanceHistoryEntry {
    /**
     * 
     * @type {string}
     * @memberof CoinBalanceHistoryEntry
     */
    transactionHash?: string;
    /**
     * 
     * @type {number}
     * @memberof CoinBalanceHistoryEntry
     */
    blockNumber: number;
    /**
     * 
     * @type {string}
     * @memberof CoinBalanceHistoryEntry
     */
    blockTimestamp: string;
    /**
     * 
     * @type {string}
     * @memberof CoinBalanceHistoryEntry
     */
    delta: string;
    /**
     * 
     * @type {string}
     * @memberof CoinBalanceHistoryEntry
     */
    value: string;
}

/**
 * Check if a given object implements the CoinBalanceHistoryEntry interface.
 */
export function instanceOfCoinBalanceHistoryEntry(value: object): boolean {
    if (!('blockNumber' in value)) return false;
    if (!('blockTimestamp' in value)) return false;
    if (!('delta' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function CoinBalanceHistoryEntryFromJSON(json: any): CoinBalanceHistoryEntry {
    return CoinBalanceHistoryEntryFromJSONTyped(json, false);
}

export function CoinBalanceHistoryEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoinBalanceHistoryEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionHash': json['transaction_hash'] == null ? undefined : json['transaction_hash'],
        'blockNumber': json['block_number'],
        'blockTimestamp': json['block_timestamp'],
        'delta': json['delta'],
        'value': json['value'],
    };
}

export function CoinBalanceHistoryEntryToJSON(value?: CoinBalanceHistoryEntry | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'transaction_hash': value['transactionHash'],
        'block_number': value['blockNumber'],
        'block_timestamp': value['blockTimestamp'],
        'delta': value['delta'],
        'value': value['value'],
    };
}

