/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecodedInputLogParameter
 */
export interface DecodedInputLogParameter {
    /**
     * 
     * @type {string}
     * @memberof DecodedInputLogParameter
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DecodedInputLogParameter
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof DecodedInputLogParameter
     */
    value: string;
    /**
     * 
     * @type {boolean}
     * @memberof DecodedInputLogParameter
     */
    indexed: boolean;
}

/**
 * Check if a given object implements the DecodedInputLogParameter interface.
 */
export function instanceOfDecodedInputLogParameter(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('type' in value)) return false;
    if (!('value' in value)) return false;
    if (!('indexed' in value)) return false;
    return true;
}

export function DecodedInputLogParameterFromJSON(json: any): DecodedInputLogParameter {
    return DecodedInputLogParameterFromJSONTyped(json, false);
}

export function DecodedInputLogParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecodedInputLogParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'value': json['value'],
        'indexed': json['indexed'],
    };
}

export function DecodedInputLogParameterToJSON(value?: DecodedInputLogParameter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'type': value['type'],
        'value': value['value'],
        'indexed': value['indexed'],
    };
}

