/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecodedInputParameter
 */
export interface DecodedInputParameter {
    /**
     * 
     * @type {string}
     * @memberof DecodedInputParameter
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DecodedInputParameter
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof DecodedInputParameter
     */
    value: string;
}

/**
 * Check if a given object implements the DecodedInputParameter interface.
 */
export function instanceOfDecodedInputParameter(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('type' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function DecodedInputParameterFromJSON(json: any): DecodedInputParameter {
    return DecodedInputParameterFromJSONTyped(json, false);
}

export function DecodedInputParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecodedInputParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'value': json['value'],
    };
}

export function DecodedInputParameterToJSON(value?: DecodedInputParameter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'type': value['type'],
        'value': value['value'],
    };
}

