/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExternalLibrary
 */
export interface ExternalLibrary {
    /**
     * 
     * @type {string}
     * @memberof ExternalLibrary
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalLibrary
     */
    addressHash: string;
}

/**
 * Check if a given object implements the ExternalLibrary interface.
 */
export function instanceOfExternalLibrary(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('addressHash' in value)) return false;
    return true;
}

export function ExternalLibraryFromJSON(json: any): ExternalLibrary {
    return ExternalLibraryFromJSONTyped(json, false);
}

export function ExternalLibraryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalLibrary {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'addressHash': json['address_hash'],
    };
}

export function ExternalLibraryToJSON(value?: ExternalLibrary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'address_hash': value['addressHash'],
    };
}

