/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtendedRevertReasonAsMap
 */
export interface ExtendedRevertReasonAsMap {
    /**
     * 
     * @type {string}
     * @memberof ExtendedRevertReasonAsMap
     */
    raw: string;
    /**
     * 
     * @type {number}
     * @memberof ExtendedRevertReasonAsMap
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof ExtendedRevertReasonAsMap
     */
    message: string;
}

/**
 * Check if a given object implements the ExtendedRevertReasonAsMap interface.
 */
export function instanceOfExtendedRevertReasonAsMap(value: object): boolean {
    if (!('raw' in value)) return false;
    if (!('code' in value)) return false;
    if (!('message' in value)) return false;
    return true;
}

export function ExtendedRevertReasonAsMapFromJSON(json: any): ExtendedRevertReasonAsMap {
    return ExtendedRevertReasonAsMapFromJSONTyped(json, false);
}

export function ExtendedRevertReasonAsMapFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtendedRevertReasonAsMap {
    if (json == null) {
        return json;
    }
    return {
        
        'raw': json['raw'],
        'code': json['code'],
        'message': json['message'],
    };
}

export function ExtendedRevertReasonAsMapToJSON(value?: ExtendedRevertReasonAsMap | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'raw': value['raw'],
        'code': value['code'],
        'message': value['message'],
    };
}

