/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GasPrice
 */
export interface GasPrice {
    /**
     * 
     * @type {number}
     * @memberof GasPrice
     */
    average: number;
    /**
     * 
     * @type {number}
     * @memberof GasPrice
     */
    fast: number;
    /**
     * 
     * @type {number}
     * @memberof GasPrice
     */
    slow: number;
}

/**
 * Check if a given object implements the GasPrice interface.
 */
export function instanceOfGasPrice(value: object): boolean {
    if (!('average' in value)) return false;
    if (!('fast' in value)) return false;
    if (!('slow' in value)) return false;
    return true;
}

export function GasPriceFromJSON(json: any): GasPrice {
    return GasPriceFromJSONTyped(json, false);
}

export function GasPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): GasPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'average': json['average'],
        'fast': json['fast'],
        'slow': json['slow'],
    };
}

export function GasPriceToJSON(value?: GasPrice | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'average': value['average'],
        'fast': value['fast'],
        'slow': value['slow'],
    };
}

