/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InternalTransaction } from './InternalTransaction';
import {
    InternalTransactionFromJSON,
    InternalTransactionFromJSONTyped,
    InternalTransactionToJSON,
} from './InternalTransaction';

/**
 * 
 * @export
 * @interface GetAddressInternalTxs200Response
 */
export interface GetAddressInternalTxs200Response {
    /**
     * 
     * @type {Array<InternalTransaction>}
     * @memberof GetAddressInternalTxs200Response
     */
    items: Array<InternalTransaction>;
    /**
     * 
     * @type {object}
     * @memberof GetAddressInternalTxs200Response
     */
    nextPageParams: object;
}

/**
 * Check if a given object implements the GetAddressInternalTxs200Response interface.
 */
export function instanceOfGetAddressInternalTxs200Response(value: object): boolean {
    if (!('items' in value)) return false;
    if (!('nextPageParams' in value)) return false;
    return true;
}

export function GetAddressInternalTxs200ResponseFromJSON(json: any): GetAddressInternalTxs200Response {
    return GetAddressInternalTxs200ResponseFromJSONTyped(json, false);
}

export function GetAddressInternalTxs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAddressInternalTxs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(InternalTransactionFromJSON)),
        'nextPageParams': json['next_page_params'],
    };
}

export function GetAddressInternalTxs200ResponseToJSON(value?: GetAddressInternalTxs200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(InternalTransactionToJSON)),
        'next_page_params': value['nextPageParams'],
    };
}

