/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressNFTCollection } from './AddressNFTCollection';
import {
    AddressNFTCollectionFromJSON,
    AddressNFTCollectionFromJSONTyped,
    AddressNFTCollectionToJSON,
} from './AddressNFTCollection';

/**
 * 
 * @export
 * @interface GetAddressNftCollections200Response
 */
export interface GetAddressNftCollections200Response {
    /**
     * 
     * @type {Array<AddressNFTCollection>}
     * @memberof GetAddressNftCollections200Response
     */
    items: Array<AddressNFTCollection>;
    /**
     * 
     * @type {object}
     * @memberof GetAddressNftCollections200Response
     */
    nextPageParams: object;
}

/**
 * Check if a given object implements the GetAddressNftCollections200Response interface.
 */
export function instanceOfGetAddressNftCollections200Response(value: object): boolean {
    if (!('items' in value)) return false;
    if (!('nextPageParams' in value)) return false;
    return true;
}

export function GetAddressNftCollections200ResponseFromJSON(json: any): GetAddressNftCollections200Response {
    return GetAddressNftCollections200ResponseFromJSONTyped(json, false);
}

export function GetAddressNftCollections200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAddressNftCollections200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AddressNFTCollectionFromJSON)),
        'nextPageParams': json['next_page_params'],
    };
}

export function GetAddressNftCollections200ResponseToJSON(value?: GetAddressNftCollections200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(AddressNFTCollectionToJSON)),
        'next_page_params': value['nextPageParams'],
    };
}

