/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenBalance } from './TokenBalance';
import {
    TokenBalanceFromJSON,
    TokenBalanceFromJSONTyped,
    TokenBalanceToJSON,
} from './TokenBalance';

/**
 * 
 * @export
 * @interface GetAddressTokens200Response
 */
export interface GetAddressTokens200Response {
    /**
     * 
     * @type {Array<TokenBalance>}
     * @memberof GetAddressTokens200Response
     */
    items: Array<TokenBalance>;
    /**
     * 
     * @type {object}
     * @memberof GetAddressTokens200Response
     */
    nextPageParams: object;
}

/**
 * Check if a given object implements the GetAddressTokens200Response interface.
 */
export function instanceOfGetAddressTokens200Response(value: object): boolean {
    if (!('items' in value)) return false;
    if (!('nextPageParams' in value)) return false;
    return true;
}

export function GetAddressTokens200ResponseFromJSON(json: any): GetAddressTokens200Response {
    return GetAddressTokens200ResponseFromJSONTyped(json, false);
}

export function GetAddressTokens200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAddressTokens200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TokenBalanceFromJSON)),
        'nextPageParams': json['next_page_params'],
    };
}

export function GetAddressTokens200ResponseToJSON(value?: GetAddressTokens200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(TokenBalanceToJSON)),
        'next_page_params': value['nextPageParams'],
    };
}

