/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NextPageParams } from './NextPageParams';
import {
    NextPageParamsFromJSON,
    NextPageParamsFromJSONTyped,
    NextPageParamsToJSON,
} from './NextPageParams';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
} from './Transaction';

/**
 * 
 * @export
 * @interface GetAddressTxs200Response
 */
export interface GetAddressTxs200Response {
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof GetAddressTxs200Response
     */
    items: Array<Transaction>;
    /**
     * 
     * @type {NextPageParams}
     * @memberof GetAddressTxs200Response
     */
    nextPageParams: NextPageParams;
}

/**
 * Check if a given object implements the GetAddressTxs200Response interface.
 */
export function instanceOfGetAddressTxs200Response(value: object): boolean {
    if (!('items' in value)) return false;
    if (!('nextPageParams' in value)) return false;
    return true;
}

export function GetAddressTxs200ResponseFromJSON(json: any): GetAddressTxs200Response {
    return GetAddressTxs200ResponseFromJSONTyped(json, false);
}

export function GetAddressTxs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAddressTxs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TransactionFromJSON)),
        'nextPageParams': NextPageParamsFromJSON(json['next_page_params']),
    };
}

export function GetAddressTxs200ResponseToJSON(value?: GetAddressTxs200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(TransactionToJSON)),
        'next_page_params': NextPageParamsToJSON(value['nextPageParams']),
    };
}

