/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Block } from './Block';
import {
    BlockFromJSON,
    BlockFromJSONTyped,
    BlockToJSON,
} from './Block';

/**
 * 
 * @export
 * @interface GetBlocks200Response
 */
export interface GetBlocks200Response {
    /**
     * 
     * @type {Array<Block>}
     * @memberof GetBlocks200Response
     */
    items: Array<Block>;
    /**
     * 
     * @type {object}
     * @memberof GetBlocks200Response
     */
    nextPageParams: object;
}

/**
 * Check if a given object implements the GetBlocks200Response interface.
 */
export function instanceOfGetBlocks200Response(value: object): boolean {
    if (!('items' in value)) return false;
    if (!('nextPageParams' in value)) return false;
    return true;
}

export function GetBlocks200ResponseFromJSON(json: any): GetBlocks200Response {
    return GetBlocks200ResponseFromJSONTyped(json, false);
}

export function GetBlocks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBlocks200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(BlockFromJSON)),
        'nextPageParams': json['next_page_params'],
    };
}

export function GetBlocks200ResponseToJSON(value?: GetBlocks200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(BlockToJSON)),
        'next_page_params': value['nextPageParams'],
    };
}

