/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Withdrawal } from './Withdrawal';
import {
    WithdrawalFromJSON,
    WithdrawalFromJSONTyped,
    WithdrawalToJSON,
} from './Withdrawal';

/**
 * 
 * @export
 * @interface GetBlockWithdrawals200Response
 */
export interface GetBlockWithdrawals200Response {
    /**
     * 
     * @type {Array<Withdrawal>}
     * @memberof GetBlockWithdrawals200Response
     */
    items: Array<Withdrawal>;
    /**
     * 
     * @type {object}
     * @memberof GetBlockWithdrawals200Response
     */
    nextPageParams: object;
}

/**
 * Check if a given object implements the GetBlockWithdrawals200Response interface.
 */
export function instanceOfGetBlockWithdrawals200Response(value: object): boolean {
    if (!('items' in value)) return false;
    if (!('nextPageParams' in value)) return false;
    return true;
}

export function GetBlockWithdrawals200ResponseFromJSON(json: any): GetBlockWithdrawals200Response {
    return GetBlockWithdrawals200ResponseFromJSONTyped(json, false);
}

export function GetBlockWithdrawals200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBlockWithdrawals200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WithdrawalFromJSON)),
        'nextPageParams': json['next_page_params'],
    };
}

export function GetBlockWithdrawals200ResponseToJSON(value?: GetBlockWithdrawals200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(WithdrawalToJSON)),
        'next_page_params': value['nextPageParams'],
    };
}

