/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetNftInstanceTransfersCount200Response
 */
export interface GetNftInstanceTransfersCount200Response {
    /**
     * 
     * @type {number}
     * @memberof GetNftInstanceTransfersCount200Response
     */
    transfersCount: number;
}

/**
 * Check if a given object implements the GetNftInstanceTransfersCount200Response interface.
 */
export function instanceOfGetNftInstanceTransfersCount200Response(value: object): boolean {
    if (!('transfersCount' in value)) return false;
    return true;
}

export function GetNftInstanceTransfersCount200ResponseFromJSON(json: any): GetNftInstanceTransfersCount200Response {
    return GetNftInstanceTransfersCount200ResponseFromJSONTyped(json, false);
}

export function GetNftInstanceTransfersCount200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNftInstanceTransfersCount200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'transfersCount': json['transfers_count'],
    };
}

export function GetNftInstanceTransfersCount200ResponseToJSON(value?: GetNftInstanceTransfersCount200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'transfers_count': value['transfersCount'],
    };
}

