/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSmartContractsCounters200Response
 */
export interface GetSmartContractsCounters200Response {
    /**
     * 
     * @type {string}
     * @memberof GetSmartContractsCounters200Response
     */
    newSmartContracts24h: string;
    /**
     * 
     * @type {string}
     * @memberof GetSmartContractsCounters200Response
     */
    newVerifiedSmartContracts24h: string;
    /**
     * 
     * @type {string}
     * @memberof GetSmartContractsCounters200Response
     */
    smartContracts: string;
    /**
     * 
     * @type {string}
     * @memberof GetSmartContractsCounters200Response
     */
    verifiedSmartContracts: string;
}

/**
 * Check if a given object implements the GetSmartContractsCounters200Response interface.
 */
export function instanceOfGetSmartContractsCounters200Response(value: object): boolean {
    if (!('newSmartContracts24h' in value)) return false;
    if (!('newVerifiedSmartContracts24h' in value)) return false;
    if (!('smartContracts' in value)) return false;
    if (!('verifiedSmartContracts' in value)) return false;
    return true;
}

export function GetSmartContractsCounters200ResponseFromJSON(json: any): GetSmartContractsCounters200Response {
    return GetSmartContractsCounters200ResponseFromJSONTyped(json, false);
}

export function GetSmartContractsCounters200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSmartContractsCounters200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'newSmartContracts24h': json['new_smart_contracts_24h'],
        'newVerifiedSmartContracts24h': json['new_verified_smart_contracts_24h'],
        'smartContracts': json['smart_contracts'],
        'verifiedSmartContracts': json['verified_smart_contracts'],
    };
}

export function GetSmartContractsCounters200ResponseToJSON(value?: GetSmartContractsCounters200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'new_smart_contracts_24h': value['newSmartContracts24h'],
        'new_verified_smart_contracts_24h': value['newVerifiedSmartContracts24h'],
        'smart_contracts': value['smartContracts'],
        'verified_smart_contracts': value['verifiedSmartContracts'],
    };
}

