/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SmartContractForList } from './SmartContractForList';
import {
    SmartContractForListFromJSON,
    SmartContractForListFromJSONTyped,
    SmartContractForListToJSON,
} from './SmartContractForList';

/**
 * 
 * @export
 * @interface GetSmartContracts200Response
 */
export interface GetSmartContracts200Response {
    /**
     * 
     * @type {Array<SmartContractForList>}
     * @memberof GetSmartContracts200Response
     */
    items: Array<SmartContractForList>;
    /**
     * 
     * @type {object}
     * @memberof GetSmartContracts200Response
     */
    nextPageParams: object;
}

/**
 * Check if a given object implements the GetSmartContracts200Response interface.
 */
export function instanceOfGetSmartContracts200Response(value: object): boolean {
    if (!('items' in value)) return false;
    if (!('nextPageParams' in value)) return false;
    return true;
}

export function GetSmartContracts200ResponseFromJSON(json: any): GetSmartContracts200Response {
    return GetSmartContracts200ResponseFromJSONTyped(json, false);
}

export function GetSmartContracts200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSmartContracts200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(SmartContractForListFromJSON)),
        'nextPageParams': json['next_page_params'],
    };
}

export function GetSmartContracts200ResponseToJSON(value?: GetSmartContracts200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(SmartContractForListToJSON)),
        'next_page_params': value['nextPageParams'],
    };
}

