/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Log } from './Log';
import {
    LogFromJSON,
    LogFromJSONTyped,
    LogToJSON,
} from './Log';

/**
 * 
 * @export
 * @interface GetTransactionLogs200Response
 */
export interface GetTransactionLogs200Response {
    /**
     * 
     * @type {Array<Log>}
     * @memberof GetTransactionLogs200Response
     */
    items: Array<Log>;
    /**
     * 
     * @type {object}
     * @memberof GetTransactionLogs200Response
     */
    nextPageParams: object;
}

/**
 * Check if a given object implements the GetTransactionLogs200Response interface.
 */
export function instanceOfGetTransactionLogs200Response(value: object): boolean {
    if (!('items' in value)) return false;
    if (!('nextPageParams' in value)) return false;
    return true;
}

export function GetTransactionLogs200ResponseFromJSON(json: any): GetTransactionLogs200Response {
    return GetTransactionLogs200ResponseFromJSONTyped(json, false);
}

export function GetTransactionLogs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTransactionLogs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(LogFromJSON)),
        'nextPageParams': json['next_page_params'],
    };
}

export function GetTransactionLogs200ResponseToJSON(value?: GetTransactionLogs200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(LogToJSON)),
        'next_page_params': value['nextPageParams'],
    };
}

