/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenInfo } from './TokenInfo';
import {
    TokenInfoFromJSON,
    TokenInfoFromJSONTyped,
    TokenInfoToJSON,
} from './TokenInfo';

/**
 * 
 * @export
 * @interface GetTokensList200Response
 */
export interface GetTokensList200Response {
    /**
     * 
     * @type {Array<TokenInfo>}
     * @memberof GetTokensList200Response
     */
    items: Array<TokenInfo>;
    /**
     * 
     * @type {object}
     * @memberof GetTokensList200Response
     */
    nextPageParams: object;
}

/**
 * Check if a given object implements the GetTokensList200Response interface.
 */
export function instanceOfGetTokensList200Response(value: object): boolean {
    if (!('items' in value)) return false;
    if (!('nextPageParams' in value)) return false;
    return true;
}

export function GetTokensList200ResponseFromJSON(json: any): GetTokensList200Response {
    return GetTokensList200ResponseFromJSONTyped(json, false);
}

export function GetTokensList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTokensList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TokenInfoFromJSON)),
        'nextPageParams': json['next_page_params'],
    };
}

export function GetTokensList200ResponseToJSON(value?: GetTokensList200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(TokenInfoToJSON)),
        'next_page_params': value['nextPageParams'],
    };
}

