/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionChartItem } from './TransactionChartItem';
import {
    TransactionChartItemFromJSON,
    TransactionChartItemFromJSONTyped,
    TransactionChartItemToJSON,
} from './TransactionChartItem';

/**
 * 
 * @export
 * @interface GetTxsChart200Response
 */
export interface GetTxsChart200Response {
    /**
     * 
     * @type {Array<TransactionChartItem>}
     * @memberof GetTxsChart200Response
     */
    chartData: Array<TransactionChartItem>;
}

/**
 * Check if a given object implements the GetTxsChart200Response interface.
 */
export function instanceOfGetTxsChart200Response(value: object): boolean {
    if (!('chartData' in value)) return false;
    return true;
}

export function GetTxsChart200ResponseFromJSON(json: any): GetTxsChart200Response {
    return GetTxsChart200ResponseFromJSONTyped(json, false);
}

export function GetTxsChart200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTxsChart200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'chartData': ((json['chart_data'] as Array<any>).map(TransactionChartItemFromJSON)),
    };
}

export function GetTxsChart200ResponseToJSON(value?: GetTxsChart200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chart_data': ((value['chartData'] as Array<any>).map(TransactionChartItemToJSON)),
    };
}

