/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenTransfer } from './TokenTransfer';
import {
    TokenTransferFromJSON,
    TokenTransferFromJSONTyped,
    TokenTransferToJSON,
} from './TokenTransfer';

/**
 * 
 * @export
 * @interface GetTokenTransfers200Response
 */
export interface GetTokenTransfers200Response {
    /**
     * 
     * @type {Array<TokenTransfer>}
     * @memberof GetTokenTransfers200Response
     */
    items: Array<TokenTransfer>;
    /**
     * 
     * @type {object}
     * @memberof GetTokenTransfers200Response
     */
    nextPageParams: object;
}

/**
 * Check if a given object implements the GetTokenTransfers200Response interface.
 */
export function instanceOfGetTokenTransfers200Response(value: object): boolean {
    if (!('items' in value)) return false;
    if (!('nextPageParams' in value)) return false;
    return true;
}

export function GetTokenTransfers200ResponseFromJSON(json: any): GetTokenTransfers200Response {
    return GetTokenTransfers200ResponseFromJSONTyped(json, false);
}

export function GetTokenTransfers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTokenTransfers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TokenTransferFromJSON)),
        'nextPageParams': json['next_page_params'],
    };
}

export function GetTokenTransfers200ResponseToJSON(value?: GetTokenTransfers200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(TokenTransferToJSON)),
        'next_page_params': value['nextPageParams'],
    };
}

