/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
} from './Transaction';

/**
 * 
 * @export
 * @interface GetTxs200Response
 */
export interface GetTxs200Response {
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof GetTxs200Response
     */
    items: Array<Transaction>;
    /**
     * 
     * @type {object}
     * @memberof GetTxs200Response
     */
    nextPageParams: object;
}

/**
 * Check if a given object implements the GetTxs200Response interface.
 */
export function instanceOfGetTxs200Response(value: object): boolean {
    if (!('items' in value)) return false;
    if (!('nextPageParams' in value)) return false;
    return true;
}

export function GetTxs200ResponseFromJSON(json: any): GetTxs200Response {
    return GetTxs200ResponseFromJSONTyped(json, false);
}

export function GetTxs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTxs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TransactionFromJSON)),
        'nextPageParams': json['next_page_params'],
    };
}

export function GetTxs200ResponseToJSON(value?: GetTxs200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(TransactionToJSON)),
        'next_page_params': value['nextPageParams'],
    };
}

