/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *  - SERVICE_UNKNOWN: Used only by the Watch method.
 * @export
 */
export const HealthCheckResponseServingStatus = {
    Unknown: "UNKNOWN",
    Serving: "SERVING",
    NotServing: "NOT_SERVING",
    ServiceUnknown: "SERVICE_UNKNOWN",
} as const;
export type HealthCheckResponseServingStatus =
    (typeof HealthCheckResponseServingStatus)[keyof typeof HealthCheckResponseServingStatus];

export function instanceOfHealthCheckResponseServingStatus(
    value: any
): boolean {
    return Object.values(HealthCheckResponseServingStatus).includes(value);
}

export function HealthCheckResponseServingStatusFromJSON(
    json: any
): HealthCheckResponseServingStatus {
    return HealthCheckResponseServingStatusFromJSONTyped(json, false);
}

export function HealthCheckResponseServingStatusFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): HealthCheckResponseServingStatus {
    return json as HealthCheckResponseServingStatus;
}

export function HealthCheckResponseServingStatusToJSON(
    value?: HealthCheckResponseServingStatus | null
): any {
    return value as any;
}
