/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressParam } from './AddressParam';
import {
    AddressParamFromJSON,
    AddressParamFromJSONTyped,
    AddressParamToJSON,
} from './AddressParam';

/**
 * 
 * @export
 * @interface Holder
 */
export interface Holder {
    /**
     * 
     * @type {AddressParam}
     * @memberof Holder
     */
    address: AddressParam;
    /**
     * 
     * @type {string}
     * @memberof Holder
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof Holder
     */
    tokenId?: string;
}

/**
 * Check if a given object implements the Holder interface.
 */
export function instanceOfHolder(value: object): boolean {
    if (!('address' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function HolderFromJSON(json: any): Holder {
    return HolderFromJSONTyped(json, false);
}

export function HolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Holder {
    if (json == null) {
        return json;
    }
    return {
        
        'address': AddressParamFromJSON(json['address']),
        'value': json['value'],
        'tokenId': json['token_id'] == null ? undefined : json['token_id'],
    };
}

export function HolderToJSON(value?: Holder | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': AddressParamToJSON(value['address']),
        'value': value['value'],
        'token_id': value['tokenId'],
    };
}

