/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndexingStatus
 */
export interface IndexingStatus {
    /**
     * 
     * @type {boolean}
     * @memberof IndexingStatus
     */
    finishedIndexing: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IndexingStatus
     */
    finishedIndexingBlocks: boolean;
    /**
     * 
     * @type {string}
     * @memberof IndexingStatus
     */
    indexedBlocksRatio: string;
    /**
     * 
     * @type {string}
     * @memberof IndexingStatus
     */
    indexedInternalTransactionsRatio: string;
}

/**
 * Check if a given object implements the IndexingStatus interface.
 */
export function instanceOfIndexingStatus(value: object): boolean {
    if (!('finishedIndexing' in value)) return false;
    if (!('finishedIndexingBlocks' in value)) return false;
    if (!('indexedBlocksRatio' in value)) return false;
    if (!('indexedInternalTransactionsRatio' in value)) return false;
    return true;
}

export function IndexingStatusFromJSON(json: any): IndexingStatus {
    return IndexingStatusFromJSONTyped(json, false);
}

export function IndexingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexingStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'finishedIndexing': json['finished_indexing'],
        'finishedIndexingBlocks': json['finished_indexing_blocks'],
        'indexedBlocksRatio': json['indexed_blocks_ratio'],
        'indexedInternalTransactionsRatio': json['indexed_internal_transactions_ratio'],
    };
}

export function IndexingStatusToJSON(value?: IndexingStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'finished_indexing': value['finishedIndexing'],
        'finished_indexing_blocks': value['finishedIndexingBlocks'],
        'indexed_blocks_ratio': value['indexedBlocksRatio'],
        'indexed_internal_transactions_ratio': value['indexedInternalTransactionsRatio'],
    };
}

