/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarketChartItem
 */
export interface MarketChartItem {
    /**
     * 
     * @type {string}
     * @memberof MarketChartItem
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof MarketChartItem
     */
    closingPrice: string;
    /**
     * 
     * @type {string}
     * @memberof MarketChartItem
     */
    marketCap: string;
}

/**
 * Check if a given object implements the MarketChartItem interface.
 */
export function instanceOfMarketChartItem(value: object): boolean {
    if (!('date' in value)) return false;
    if (!('closingPrice' in value)) return false;
    if (!('marketCap' in value)) return false;
    return true;
}

export function MarketChartItemFromJSON(json: any): MarketChartItem {
    return MarketChartItemFromJSONTyped(json, false);
}

export function MarketChartItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketChartItem {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'closingPrice': json['closing_price'],
        'marketCap': json['market_cap'],
    };
}

export function MarketChartItemToJSON(value?: MarketChartItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'date': value['date'],
        'closing_price': value['closingPrice'],
        'market_cap': value['marketCap'],
    };
}

