/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NextPageParams
 */
export interface NextPageParams {
    /**
     * 
     * @type {string}
     * @memberof NextPageParams
     */
    blockNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof NextPageParams
     */
    fee?: string;
    /**
     * 
     * @type {string}
     * @memberof NextPageParams
     */
    hash?: string;
    /**
     * 
     * @type {number}
     * @memberof NextPageParams
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof NextPageParams
     */
    insertedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof NextPageParams
     */
    itemsCount?: number;
    /**
     * 
     * @type {string}
     * @memberof NextPageParams
     */
    value?: string;
}

/**
 * Check if a given object implements the NextPageParams interface.
 */
export function instanceOfNextPageParams(value: object): boolean {
    return true;
}

export function NextPageParamsFromJSON(json: any): NextPageParams {
    return NextPageParamsFromJSONTyped(json, false);
}

export function NextPageParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NextPageParams {
    if (json == null) {
        return json;
    }
    return {
        
        'blockNumber': json['block_number'] == null ? undefined : json['block_number'],
        'fee': json['fee'] == null ? undefined : json['fee'],
        'hash': json['hash'] == null ? undefined : json['hash'],
        'index': json['index'] == null ? undefined : json['index'],
        'insertedAt': json['inserted_at'] == null ? undefined : json['inserted_at'],
        'itemsCount': json['items_count'] == null ? undefined : json['items_count'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function NextPageParamsToJSON(value?: NextPageParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'block_number': value['blockNumber'],
        'fee': value['fee'],
        'hash': value['hash'],
        'index': value['index'],
        'inserted_at': value['insertedAt'],
        'items_count': value['itemsCount'],
        'value': value['value'],
    };
}

