/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TotalERC721 } from './TotalERC721';
import {
    TotalERC721FromJSON,
    TotalERC721FromJSONTyped,
    TotalERC721ToJSON,
} from './TotalERC721';

/**
 * 
 * @export
 * @interface NFTChange
 */
export interface NFTChange {
    /**
     * 
     * @type {string}
     * @memberof NFTChange
     */
    direction: string;
    /**
     * 
     * @type {TotalERC721}
     * @memberof NFTChange
     */
    total: TotalERC721;
}

/**
 * Check if a given object implements the NFTChange interface.
 */
export function instanceOfNFTChange(value: object): boolean {
    if (!('direction' in value)) return false;
    if (!('total' in value)) return false;
    return true;
}

export function NFTChangeFromJSON(json: any): NFTChange {
    return NFTChangeFromJSONTyped(json, false);
}

export function NFTChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NFTChange {
    if (json == null) {
        return json;
    }
    return {
        
        'direction': json['direction'],
        'total': TotalERC721FromJSON(json['total']),
    };
}

export function NFTChangeToJSON(value?: NFTChange | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'direction': value['direction'],
        'total': TotalERC721ToJSON(value['total']),
    };
}

