/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressParam } from './AddressParam';
import {
    AddressParamFromJSON,
    AddressParamFromJSONTyped,
    AddressParamToJSON,
} from './AddressParam';
import type { TokenInfo } from './TokenInfo';
import {
    TokenInfoFromJSON,
    TokenInfoFromJSONTyped,
    TokenInfoToJSON,
} from './TokenInfo';

/**
 * 
 * @export
 * @interface NFTInstance
 */
export interface NFTInstance {
    /**
     * 
     * @type {boolean}
     * @memberof NFTInstance
     */
    isUnique: boolean;
    /**
     * 
     * @type {string}
     * @memberof NFTInstance
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof NFTInstance
     */
    holderAddressHash?: string;
    /**
     * 
     * @type {string}
     * @memberof NFTInstance
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof NFTInstance
     */
    animationUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof NFTInstance
     */
    externalAppUrl?: string;
    /**
     * 
     * @type {object}
     * @memberof NFTInstance
     */
    metadata?: object;
    /**
     * 
     * @type {AddressParam}
     * @memberof NFTInstance
     */
    owner: AddressParam;
    /**
     * 
     * @type {TokenInfo}
     * @memberof NFTInstance
     */
    token: TokenInfo;
}

/**
 * Check if a given object implements the NFTInstance interface.
 */
export function instanceOfNFTInstance(value: object): boolean {
    if (!('isUnique' in value)) return false;
    if (!('id' in value)) return false;
    if (!('owner' in value)) return false;
    if (!('token' in value)) return false;
    return true;
}

export function NFTInstanceFromJSON(json: any): NFTInstance {
    return NFTInstanceFromJSONTyped(json, false);
}

export function NFTInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NFTInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'isUnique': json['is_unique'],
        'id': json['id'],
        'holderAddressHash': json['holder_address_hash'] == null ? undefined : json['holder_address_hash'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'animationUrl': json['animation_url'] == null ? undefined : json['animation_url'],
        'externalAppUrl': json['external_app_url'] == null ? undefined : json['external_app_url'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'owner': AddressParamFromJSON(json['owner']),
        'token': TokenInfoFromJSON(json['token']),
    };
}

export function NFTInstanceToJSON(value?: NFTInstance | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'is_unique': value['isUnique'],
        'id': value['id'],
        'holder_address_hash': value['holderAddressHash'],
        'image_url': value['imageUrl'],
        'animation_url': value['animationUrl'],
        'external_app_url': value['externalAppUrl'],
        'metadata': value['metadata'],
        'owner': AddressParamToJSON(value['owner']),
        'token': TokenInfoToJSON(value['token']),
    };
}

