/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OutputAndNamesOutputInner
 */
export interface OutputAndNamesOutputInner {
}

/**
 * Check if a given object implements the OutputAndNamesOutputInner interface.
 */
export function instanceOfOutputAndNamesOutputInner(value: object): boolean {
    return true;
}

export function OutputAndNamesOutputInnerFromJSON(json: any): OutputAndNamesOutputInner {
    return OutputAndNamesOutputInnerFromJSONTyped(json, false);
}

export function OutputAndNamesOutputInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputAndNamesOutputInner {
    return json;
}

export function OutputAndNamesOutputInnerToJSON(value?: OutputAndNamesOutputInner | null): any {
    return value;
}

