/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OutputAndNamesOutputInner } from './OutputAndNamesOutputInner';
import {
    OutputAndNamesOutputInnerFromJSON,
    OutputAndNamesOutputInnerFromJSONTyped,
    OutputAndNamesOutputInnerToJSON,
} from './OutputAndNamesOutputInner';

/**
 * 
 * @export
 * @interface OutputAndNames
 */
export interface OutputAndNames {
    /**
     * 
     * @type {Array<OutputAndNamesOutputInner>}
     * @memberof OutputAndNames
     */
    output: Array<OutputAndNamesOutputInner>;
    /**
     * 
     * @type {Array<OutputAndNamesOutputInner>}
     * @memberof OutputAndNames
     */
    names: Array<OutputAndNamesOutputInner>;
}

/**
 * Check if a given object implements the OutputAndNames interface.
 */
export function instanceOfOutputAndNames(value: object): boolean {
    if (!('output' in value)) return false;
    if (!('names' in value)) return false;
    return true;
}

export function OutputAndNamesFromJSON(json: any): OutputAndNames {
    return OutputAndNamesFromJSONTyped(json, false);
}

export function OutputAndNamesFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputAndNames {
    if (json == null) {
        return json;
    }
    return {
        
        'output': ((json['output'] as Array<any>).map(OutputAndNamesOutputInnerFromJSON)),
        'names': ((json['names'] as Array<any>).map(OutputAndNamesOutputInnerFromJSON)),
    };
}

export function OutputAndNamesToJSON(value?: OutputAndNames | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'output': ((value['output'] as Array<any>).map(OutputAndNamesOutputInnerToJSON)),
        'names': ((value['names'] as Array<any>).map(OutputAndNamesOutputInnerToJSON)),
    };
}

