/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProtobufAny
 */
export interface ProtobufAny {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ProtobufAny
     */
    type?: string;
}

/**
 * Check if a given object implements the ProtobufAny interface.
 */
export function instanceOfProtobufAny(value: object): boolean {
    return true;
}

export function ProtobufAnyFromJSON(json: any): ProtobufAny {
    return ProtobufAnyFromJSONTyped(json, false);
}

export function ProtobufAnyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProtobufAny {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['@type'] == null ? undefined : json['@type'],
    };
}

export function ProtobufAnyToJSON(value?: ProtobufAny | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        '@type': value['type'],
    };
}

