/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RawTraceCreateAction
 */
export interface RawTraceCreateAction {
    /**
     * 
     * @type {string}
     * @memberof RawTraceCreateAction
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof RawTraceCreateAction
     */
    gas: string;
    /**
     * 
     * @type {string}
     * @memberof RawTraceCreateAction
     */
    init: string;
    /**
     * 
     * @type {string}
     * @memberof RawTraceCreateAction
     */
    value: string;
}

/**
 * Check if a given object implements the RawTraceCreateAction interface.
 */
export function instanceOfRawTraceCreateAction(value: object): boolean {
    if (!('from' in value)) return false;
    if (!('gas' in value)) return false;
    if (!('init' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function RawTraceCreateActionFromJSON(json: any): RawTraceCreateAction {
    return RawTraceCreateActionFromJSONTyped(json, false);
}

export function RawTraceCreateActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawTraceCreateAction {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'],
        'gas': json['gas'],
        'init': json['init'],
        'value': json['value'],
    };
}

export function RawTraceCreateActionToJSON(value?: RawTraceCreateAction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'from': value['from'],
        'gas': value['gas'],
        'init': value['init'],
        'value': value['value'],
    };
}

