/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RawTraceCreateResult
 */
export interface RawTraceCreateResult {
    /**
     * 
     * @type {string}
     * @memberof RawTraceCreateResult
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof RawTraceCreateResult
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof RawTraceCreateResult
     */
    gasUsed: string;
}

/**
 * Check if a given object implements the RawTraceCreateResult interface.
 */
export function instanceOfRawTraceCreateResult(value: object): boolean {
    if (!('address' in value)) return false;
    if (!('code' in value)) return false;
    if (!('gasUsed' in value)) return false;
    return true;
}

export function RawTraceCreateResultFromJSON(json: any): RawTraceCreateResult {
    return RawTraceCreateResultFromJSONTyped(json, false);
}

export function RawTraceCreateResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawTraceCreateResult {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'code': json['code'],
        'gasUsed': json['gasUsed'],
    };
}

export function RawTraceCreateResultToJSON(value?: RawTraceCreateResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': value['address'],
        'code': value['code'],
        'gasUsed': value['gasUsed'],
    };
}

