/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RawTraceCallResult
 */
export interface RawTraceCallResult {
    /**
     * 
     * @type {string}
     * @memberof RawTraceCallResult
     */
    gasUsed: string;
    /**
     * 
     * @type {string}
     * @memberof RawTraceCallResult
     */
    output: string;
}

/**
 * Check if a given object implements the RawTraceCallResult interface.
 */
export function instanceOfRawTraceCallResult(value: object): boolean {
    if (!('gasUsed' in value)) return false;
    if (!('output' in value)) return false;
    return true;
}

export function RawTraceCallResultFromJSON(json: any): RawTraceCallResult {
    return RawTraceCallResultFromJSONTyped(json, false);
}

export function RawTraceCallResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawTraceCallResult {
    if (json == null) {
        return json;
    }
    return {
        
        'gasUsed': json['gasUsed'],
        'output': json['output'],
    };
}

export function RawTraceCallResultToJSON(value?: RawTraceCallResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'gasUsed': value['gasUsed'],
        'output': value['output'],
    };
}

