/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecaptchaBody
 */
export interface RecaptchaBody {
    /**
     * 
     * @type {string}
     * @memberof RecaptchaBody
     */
    recaptchaResponse: string;
}

/**
 * Check if a given object implements the RecaptchaBody interface.
 */
export function instanceOfRecaptchaBody(value: object): boolean {
    if (!('recaptchaResponse' in value)) return false;
    return true;
}

export function RecaptchaBodyFromJSON(json: any): RecaptchaBody {
    return RecaptchaBodyFromJSONTyped(json, false);
}

export function RecaptchaBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecaptchaBody {
    if (json == null) {
        return json;
    }
    return {
        
        'recaptchaResponse': json['recaptcha_response'],
    };
}

export function RecaptchaBodyToJSON(value?: RecaptchaBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'recaptcha_response': value['recaptchaResponse'],
    };
}

