/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefetchTokenInstanceMetadata200Response
 */
export interface RefetchTokenInstanceMetadata200Response {
    /**
     * 
     * @type {string}
     * @memberof RefetchTokenInstanceMetadata200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the RefetchTokenInstanceMetadata200Response interface.
 */
export function instanceOfRefetchTokenInstanceMetadata200Response(value: object): boolean {
    return true;
}

export function RefetchTokenInstanceMetadata200ResponseFromJSON(json: any): RefetchTokenInstanceMetadata200Response {
    return RefetchTokenInstanceMetadata200ResponseFromJSONTyped(json, false);
}

export function RefetchTokenInstanceMetadata200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefetchTokenInstanceMetadata200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function RefetchTokenInstanceMetadata200ResponseToJSON(value?: RefetchTokenInstanceMetadata200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

