/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Reward
 */
export interface Reward {
    /**
     * 
     * @type {number}
     * @memberof Reward
     */
    reward: number;
    /**
     * 
     * @type {string}
     * @memberof Reward
     */
    type: string;
}

/**
 * Check if a given object implements the Reward interface.
 */
export function instanceOfReward(value: object): boolean {
    if (!('reward' in value)) return false;
    if (!('type' in value)) return false;
    return true;
}

export function RewardFromJSON(json: any): Reward {
    return RewardFromJSONTyped(json, false);
}

export function RewardFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reward {
    if (json == null) {
        return json;
    }
    return {
        
        'reward': json['reward'],
        'type': json['type'],
    };
}

export function RewardToJSON(value?: Reward | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'reward': value['reward'],
        'type': value['type'],
    };
}

