/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchResultRedirect
 */
export interface SearchResultRedirect {
    /**
     * 
     * @type {string}
     * @memberof SearchResultRedirect
     */
    parameter: string;
    /**
     * 
     * @type {boolean}
     * @memberof SearchResultRedirect
     */
    redirect: boolean;
    /**
     * 
     * @type {string}
     * @memberof SearchResultRedirect
     */
    type: string;
}

/**
 * Check if a given object implements the SearchResultRedirect interface.
 */
export function instanceOfSearchResultRedirect(value: object): boolean {
    if (!('parameter' in value)) return false;
    if (!('redirect' in value)) return false;
    if (!('type' in value)) return false;
    return true;
}

export function SearchResultRedirectFromJSON(json: any): SearchResultRedirect {
    return SearchResultRedirectFromJSONTyped(json, false);
}

export function SearchResultRedirectFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultRedirect {
    if (json == null) {
        return json;
    }
    return {
        
        'parameter': json['parameter'],
        'redirect': json['redirect'],
        'type': json['type'],
    };
}

export function SearchResultRedirectToJSON(value?: SearchResultRedirect | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'parameter': value['parameter'],
        'redirect': value['redirect'],
        'type': value['type'],
    };
}

