/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchResultAddressOrContract
 */
export interface SearchResultAddressOrContract {
    /**
     * 
     * @type {string}
     * @memberof SearchResultAddressOrContract
     */
    address: string;
    /**
     * 
     * @type {boolean}
     * @memberof SearchResultAddressOrContract
     */
    isSmartContractVerified: boolean;
    /**
     * 
     * @type {string}
     * @memberof SearchResultAddressOrContract
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResultAddressOrContract
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResultAddressOrContract
     */
    url: string;
}

/**
 * Check if a given object implements the SearchResultAddressOrContract interface.
 */
export function instanceOfSearchResultAddressOrContract(value: object): boolean {
    if (!('address' in value)) return false;
    if (!('isSmartContractVerified' in value)) return false;
    if (!('name' in value)) return false;
    if (!('type' in value)) return false;
    if (!('url' in value)) return false;
    return true;
}

export function SearchResultAddressOrContractFromJSON(json: any): SearchResultAddressOrContract {
    return SearchResultAddressOrContractFromJSONTyped(json, false);
}

export function SearchResultAddressOrContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultAddressOrContract {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'isSmartContractVerified': json['is_smart_contract_verified'],
        'name': json['name'],
        'type': json['type'],
        'url': json['url'],
    };
}

export function SearchResultAddressOrContractToJSON(value?: SearchResultAddressOrContract | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': value['address'],
        'is_smart_contract_verified': value['isSmartContractVerified'],
        'name': value['name'],
        'type': value['type'],
        'url': value['url'],
    };
}

