/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SearchResultAddressOrContract } from './SearchResultAddressOrContract';
import {
    instanceOfSearchResultAddressOrContract,
    SearchResultAddressOrContractFromJSON,
    SearchResultAddressOrContractFromJSONTyped,
    SearchResultAddressOrContractToJSON,
} from './SearchResultAddressOrContract';
import type { SearchResultBlock } from './SearchResultBlock';
import {
    instanceOfSearchResultBlock,
    SearchResultBlockFromJSON,
    SearchResultBlockFromJSONTyped,
    SearchResultBlockToJSON,
} from './SearchResultBlock';
import type { SearchResultToken } from './SearchResultToken';
import {
    instanceOfSearchResultToken,
    SearchResultTokenFromJSON,
    SearchResultTokenFromJSONTyped,
    SearchResultTokenToJSON,
} from './SearchResultToken';
import type { SearchResultTransaction } from './SearchResultTransaction';
import {
    instanceOfSearchResultTransaction,
    SearchResultTransactionFromJSON,
    SearchResultTransactionFromJSONTyped,
    SearchResultTransactionToJSON,
} from './SearchResultTransaction';

/**
 * @type Search200ResponseItemsInner
 * 
 * @export
 */
export type Search200ResponseItemsInner = SearchResultAddressOrContract | SearchResultBlock | SearchResultToken | SearchResultTransaction;

export function Search200ResponseItemsInnerFromJSON(json: any): Search200ResponseItemsInner {
    return Search200ResponseItemsInnerFromJSONTyped(json, false);
}

export function Search200ResponseItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Search200ResponseItemsInner {
    if (json == null) {
        return json;
    }
    return SearchResultAddressOrContractFromJSONTyped(json, true) || SearchResultBlockFromJSONTyped(json, true) || SearchResultTokenFromJSONTyped(json, true) || SearchResultTransactionFromJSONTyped(json, true);
}

export function Search200ResponseItemsInnerToJSON(value?: Search200ResponseItemsInner | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfSearchResultAddressOrContract(value)) {
        return SearchResultAddressOrContractToJSON(value as SearchResultAddressOrContract);
    }
    if (instanceOfSearchResultBlock(value)) {
        return SearchResultBlockToJSON(value as SearchResultBlock);
    }
    if (instanceOfSearchResultToken(value)) {
        return SearchResultTokenToJSON(value as SearchResultToken);
    }
    if (instanceOfSearchResultTransaction(value)) {
        return SearchResultTransactionToJSON(value as SearchResultTransaction);
    }

    return {};
}

