/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContractSource } from './ContractSource';
import {
    ContractSourceFromJSON,
    ContractSourceFromJSONTyped,
    ContractSourceToJSON,
} from './ContractSource';
import type { ExternalLibrary } from './ExternalLibrary';
import {
    ExternalLibraryFromJSON,
    ExternalLibraryFromJSONTyped,
    ExternalLibraryToJSON,
} from './ExternalLibrary';

/**
 * 
 * @export
 * @interface SmartContract
 */
export interface SmartContract {
    /**
     * 
     * @type {string}
     * @memberof SmartContract
     */
    verifiedTwinAddressHash?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SmartContract
     */
    isVerified?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SmartContract
     */
    isChangedBytecode?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SmartContract
     */
    isPartiallyVerified?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SmartContract
     */
    isFullyVerified?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SmartContract
     */
    isVerifiedViaSourcify?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SmartContract
     */
    isVerifiedViaEthBytecodeDb?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SmartContract
     */
    isVyperContract?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SmartContract
     */
    isSelfDestructed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SmartContract
     */
    canBeVisualizedViaSol2uml?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SmartContract
     */
    minimalProxyAddressHash?: string;
    /**
     * 
     * @type {string}
     * @memberof SmartContract
     */
    sourcifyRepoUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof SmartContract
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SmartContract
     */
    optimizationEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SmartContract
     */
    optimizationsRuns?: number;
    /**
     * 
     * @type {string}
     * @memberof SmartContract
     */
    compilerVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof SmartContract
     */
    evmVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof SmartContract
     */
    verifiedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof SmartContract
     */
    abi?: string;
    /**
     * 
     * @type {string}
     * @memberof SmartContract
     */
    sourceCode?: string;
    /**
     * 
     * @type {string}
     * @memberof SmartContract
     */
    filePath?: string;
    /**
     * 
     * @type {object}
     * @memberof SmartContract
     */
    compilerSettings?: object;
    /**
     * 
     * @type {string}
     * @memberof SmartContract
     */
    constructorArgs?: string;
    /**
     * 
     * @type {Array<ContractSource>}
     * @memberof SmartContract
     */
    additionalSources?: Array<ContractSource>;
    /**
     * 
     * @type {Array<object>}
     * @memberof SmartContract
     */
    decodedConstructorArgs?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof SmartContract
     */
    deployedBytecode?: string;
    /**
     * 
     * @type {string}
     * @memberof SmartContract
     */
    creationBytecode?: string;
    /**
     * 
     * @type {Array<ExternalLibrary>}
     * @memberof SmartContract
     */
    externalLibraries?: Array<ExternalLibrary>;
    /**
     * 
     * @type {string}
     * @memberof SmartContract
     */
    language?: string;
}

/**
 * Check if a given object implements the SmartContract interface.
 */
export function instanceOfSmartContract(value: object): boolean {
    return true;
}

export function SmartContractFromJSON(json: any): SmartContract {
    return SmartContractFromJSONTyped(json, false);
}

export function SmartContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmartContract {
    if (json == null) {
        return json;
    }
    return {
        
        'verifiedTwinAddressHash': json['verified_twin_address_hash'] == null ? undefined : json['verified_twin_address_hash'],
        'isVerified': json['is_verified'] == null ? undefined : json['is_verified'],
        'isChangedBytecode': json['is_changed_bytecode'] == null ? undefined : json['is_changed_bytecode'],
        'isPartiallyVerified': json['is_partially_verified'] == null ? undefined : json['is_partially_verified'],
        'isFullyVerified': json['is_fully_verified'] == null ? undefined : json['is_fully_verified'],
        'isVerifiedViaSourcify': json['is_verified_via_sourcify'] == null ? undefined : json['is_verified_via_sourcify'],
        'isVerifiedViaEthBytecodeDb': json['is_verified_via_eth_bytecode_db'] == null ? undefined : json['is_verified_via_eth_bytecode_db'],
        'isVyperContract': json['is_vyper_contract'] == null ? undefined : json['is_vyper_contract'],
        'isSelfDestructed': json['is_self_destructed'] == null ? undefined : json['is_self_destructed'],
        'canBeVisualizedViaSol2uml': json['can_be_visualized_via_sol2uml'] == null ? undefined : json['can_be_visualized_via_sol2uml'],
        'minimalProxyAddressHash': json['minimal_proxy_address_hash'] == null ? undefined : json['minimal_proxy_address_hash'],
        'sourcifyRepoUrl': json['sourcify_repo_url'] == null ? undefined : json['sourcify_repo_url'],
        'name': json['name'] == null ? undefined : json['name'],
        'optimizationEnabled': json['optimization_enabled'] == null ? undefined : json['optimization_enabled'],
        'optimizationsRuns': json['optimizations_runs'] == null ? undefined : json['optimizations_runs'],
        'compilerVersion': json['compiler_version'] == null ? undefined : json['compiler_version'],
        'evmVersion': json['evm_version'] == null ? undefined : json['evm_version'],
        'verifiedAt': json['verified_at'] == null ? undefined : json['verified_at'],
        'abi': json['abi'] == null ? undefined : json['abi'],
        'sourceCode': json['source_code'] == null ? undefined : json['source_code'],
        'filePath': json['file_path'] == null ? undefined : json['file_path'],
        'compilerSettings': json['compiler_settings'] == null ? undefined : json['compiler_settings'],
        'constructorArgs': json['constructor_args'] == null ? undefined : json['constructor_args'],
        'additionalSources': json['additional_sources'] == null ? undefined : ((json['additional_sources'] as Array<any>).map(ContractSourceFromJSON)),
        'decodedConstructorArgs': json['decoded_constructor_args'] == null ? undefined : json['decoded_constructor_args'],
        'deployedBytecode': json['deployed_bytecode'] == null ? undefined : json['deployed_bytecode'],
        'creationBytecode': json['creation_bytecode'] == null ? undefined : json['creation_bytecode'],
        'externalLibraries': json['external_libraries'] == null ? undefined : ((json['external_libraries'] as Array<any>).map(ExternalLibraryFromJSON)),
        'language': json['language'] == null ? undefined : json['language'],
    };
}

export function SmartContractToJSON(value?: SmartContract | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'verified_twin_address_hash': value['verifiedTwinAddressHash'],
        'is_verified': value['isVerified'],
        'is_changed_bytecode': value['isChangedBytecode'],
        'is_partially_verified': value['isPartiallyVerified'],
        'is_fully_verified': value['isFullyVerified'],
        'is_verified_via_sourcify': value['isVerifiedViaSourcify'],
        'is_verified_via_eth_bytecode_db': value['isVerifiedViaEthBytecodeDb'],
        'is_vyper_contract': value['isVyperContract'],
        'is_self_destructed': value['isSelfDestructed'],
        'can_be_visualized_via_sol2uml': value['canBeVisualizedViaSol2uml'],
        'minimal_proxy_address_hash': value['minimalProxyAddressHash'],
        'sourcify_repo_url': value['sourcifyRepoUrl'],
        'name': value['name'],
        'optimization_enabled': value['optimizationEnabled'],
        'optimizations_runs': value['optimizationsRuns'],
        'compiler_version': value['compilerVersion'],
        'evm_version': value['evmVersion'],
        'verified_at': value['verifiedAt'],
        'abi': value['abi'],
        'source_code': value['sourceCode'],
        'file_path': value['filePath'],
        'compiler_settings': value['compilerSettings'],
        'constructor_args': value['constructorArgs'],
        'additional_sources': value['additionalSources'] == null ? undefined : ((value['additionalSources'] as Array<any>).map(ContractSourceToJSON)),
        'decoded_constructor_args': value['decodedConstructorArgs'],
        'deployed_bytecode': value['deployedBytecode'],
        'creation_bytecode': value['creationBytecode'],
        'external_libraries': value['externalLibraries'] == null ? undefined : ((value['externalLibraries'] as Array<any>).map(ExternalLibraryToJSON)),
        'language': value['language'],
    };
}

