/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenInfoDetailed } from './TokenInfoDetailed';
import {
    TokenInfoDetailedFromJSON,
    TokenInfoDetailedFromJSONTyped,
    TokenInfoDetailedToJSON,
} from './TokenInfoDetailed';

/**
 * 
 * @export
 * @interface SummaryVariableToken
 */
export interface SummaryVariableToken {
    /**
     * Type
     * @type {string}
     * @memberof SummaryVariableToken
     */
    type: string;
    /**
     * 
     * @type {TokenInfoDetailed}
     * @memberof SummaryVariableToken
     */
    value: TokenInfoDetailed;
}

/**
 * Check if a given object implements the SummaryVariableToken interface.
 */
export function instanceOfSummaryVariableToken(value: object): boolean {
    if (!('type' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function SummaryVariableTokenFromJSON(json: any): SummaryVariableToken {
    return SummaryVariableTokenFromJSONTyped(json, false);
}

export function SummaryVariableTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): SummaryVariableToken {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': TokenInfoDetailedFromJSON(json['value']),
    };
}

export function SummaryVariableTokenToJSON(value?: SummaryVariableToken | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'value': TokenInfoDetailedToJSON(value['value']),
    };
}

