/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SummaryVariable
 */
export interface SummaryVariable {
    /**
     * Variable type
     * @type {string}
     * @memberof SummaryVariable
     */
    type: string;
    /**
     * Action Type
     * @type {string}
     * @memberof SummaryVariable
     */
    value: string;
}

/**
 * Check if a given object implements the SummaryVariable interface.
 */
export function instanceOfSummaryVariable(value: object): boolean {
    if (!('type' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function SummaryVariableFromJSON(json: any): SummaryVariable {
    return SummaryVariableFromJSONTyped(json, false);
}

export function SummaryVariableFromJSONTyped(json: any, ignoreDiscriminator: boolean): SummaryVariable {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': json['value'],
    };
}

export function SummaryVariableToJSON(value?: SummaryVariable | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'value': value['value'],
    };
}

