/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SummaryVariableCurrency
 */
export interface SummaryVariableCurrency {
    /**
     * Currency type
     * @type {string}
     * @memberof SummaryVariableCurrency
     */
    type: string;
    /**
     * Value
     * @type {string}
     * @memberof SummaryVariableCurrency
     */
    value: string;
}

/**
 * Check if a given object implements the SummaryVariableCurrency interface.
 */
export function instanceOfSummaryVariableCurrency(value: object): boolean {
    if (!('type' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function SummaryVariableCurrencyFromJSON(json: any): SummaryVariableCurrency {
    return SummaryVariableCurrencyFromJSONTyped(json, false);
}

export function SummaryVariableCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SummaryVariableCurrency {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': json['value'],
    };
}

export function SummaryVariableCurrencyToJSON(value?: SummaryVariableCurrency | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'value': value['value'],
    };
}

