/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SummaryTemplateVariables } from './SummaryTemplateVariables';
import {
    SummaryTemplateVariablesFromJSON,
    SummaryTemplateVariablesFromJSONTyped,
    SummaryTemplateVariablesToJSON,
} from './SummaryTemplateVariables';

/**
 * 
 * @export
 * @interface Summary
 */
export interface Summary {
    /**
     * Summary template
     * @type {string}
     * @memberof Summary
     */
    summaryTemplate: string;
    /**
     * 
     * @type {SummaryTemplateVariables}
     * @memberof Summary
     */
    summaryTemplateVariables: SummaryTemplateVariables;
}

/**
 * Check if a given object implements the Summary interface.
 */
export function instanceOfSummary(value: object): boolean {
    if (!('summaryTemplate' in value)) return false;
    if (!('summaryTemplateVariables' in value)) return false;
    return true;
}

export function SummaryFromJSON(json: any): Summary {
    return SummaryFromJSONTyped(json, false);
}

export function SummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Summary {
    if (json == null) {
        return json;
    }
    return {
        
        'summaryTemplate': json['summary_template'],
        'summaryTemplateVariables': SummaryTemplateVariablesFromJSON(json['summary_template_variables']),
    };
}

export function SummaryToJSON(value?: Summary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'summary_template': value['summaryTemplate'],
        'summary_template_variables': SummaryTemplateVariablesToJSON(value['summaryTemplateVariables']),
    };
}

