/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SummaryVariable } from './SummaryVariable';
import {
    SummaryVariableFromJSON,
    SummaryVariableFromJSONTyped,
    SummaryVariableToJSON,
} from './SummaryVariable';
import type { SummaryVariableCurrency } from './SummaryVariableCurrency';
import {
    SummaryVariableCurrencyFromJSON,
    SummaryVariableCurrencyFromJSONTyped,
    SummaryVariableCurrencyToJSON,
} from './SummaryVariableCurrency';
import type { SummaryVariableToken } from './SummaryVariableToken';
import {
    SummaryVariableTokenFromJSON,
    SummaryVariableTokenFromJSONTyped,
    SummaryVariableTokenToJSON,
} from './SummaryVariableToken';

/**
 * 
 * @export
 * @interface SummaryTemplateVariables
 */
export interface SummaryTemplateVariables {
    /**
     * 
     * @type {SummaryVariable}
     * @memberof SummaryTemplateVariables
     */
    actionType: SummaryVariable;
    /**
     * 
     * @type {SummaryVariableCurrency}
     * @memberof SummaryTemplateVariables
     */
    amount: SummaryVariableCurrency;
    /**
     * 
     * @type {SummaryVariableToken}
     * @memberof SummaryTemplateVariables
     */
    token: SummaryVariableToken;
}

/**
 * Check if a given object implements the SummaryTemplateVariables interface.
 */
export function instanceOfSummaryTemplateVariables(value: object): boolean {
    if (!('actionType' in value)) return false;
    if (!('amount' in value)) return false;
    if (!('token' in value)) return false;
    return true;
}

export function SummaryTemplateVariablesFromJSON(json: any): SummaryTemplateVariables {
    return SummaryTemplateVariablesFromJSONTyped(json, false);
}

export function SummaryTemplateVariablesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SummaryTemplateVariables {
    if (json == null) {
        return json;
    }
    return {
        
        'actionType': SummaryVariableFromJSON(json['action_type']),
        'amount': SummaryVariableCurrencyFromJSON(json['amount']),
        'token': SummaryVariableTokenFromJSON(json['token']),
    };
}

export function SummaryTemplateVariablesToJSON(value?: SummaryTemplateVariables | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'action_type': SummaryVariableToJSON(value['actionType']),
        'amount': SummaryVariableCurrencyToJSON(value['amount']),
        'token': SummaryVariableTokenToJSON(value['token']),
    };
}

