/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenInfo
 */
export interface TokenInfo {
    /**
     * 
     * @type {string}
     * @memberof TokenInfo
     */
    circulatingMarketCap: string;
    /**
     * 
     * @type {string}
     * @memberof TokenInfo
     */
    iconUrl: string;
    /**
     * 
     * @type {string}
     * @memberof TokenInfo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TokenInfo
     */
    decimals: string;
    /**
     * 
     * @type {string}
     * @memberof TokenInfo
     */
    symbol: string;
    /**
     * 
     * @type {string}
     * @memberof TokenInfo
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof TokenInfo
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof TokenInfo
     */
    holders: string;
    /**
     * 
     * @type {string}
     * @memberof TokenInfo
     */
    exchangeRate: string;
    /**
     * 
     * @type {string}
     * @memberof TokenInfo
     */
    totalSupply: string;
}

/**
 * Check if a given object implements the TokenInfo interface.
 */
export function instanceOfTokenInfo(value: object): boolean {
    if (!('circulatingMarketCap' in value)) return false;
    if (!('iconUrl' in value)) return false;
    if (!('name' in value)) return false;
    if (!('decimals' in value)) return false;
    if (!('symbol' in value)) return false;
    if (!('address' in value)) return false;
    if (!('type' in value)) return false;
    if (!('holders' in value)) return false;
    if (!('exchangeRate' in value)) return false;
    if (!('totalSupply' in value)) return false;
    return true;
}

export function TokenInfoFromJSON(json: any): TokenInfo {
    return TokenInfoFromJSONTyped(json, false);
}

export function TokenInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'circulatingMarketCap': json['circulating_market_cap'],
        'iconUrl': json['icon_url'],
        'name': json['name'],
        'decimals': json['decimals'],
        'symbol': json['symbol'],
        'address': json['address'],
        'type': json['type'],
        'holders': json['holders'],
        'exchangeRate': json['exchange_rate'],
        'totalSupply': json['total_supply'],
    };
}

export function TokenInfoToJSON(value?: TokenInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'circulating_market_cap': value['circulatingMarketCap'],
        'icon_url': value['iconUrl'],
        'name': value['name'],
        'decimals': value['decimals'],
        'symbol': value['symbol'],
        'address': value['address'],
        'type': value['type'],
        'holders': value['holders'],
        'exchange_rate': value['exchangeRate'],
        'total_supply': value['totalSupply'],
    };
}

