/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TotalERC1155 } from './TotalERC1155';
import {
    instanceOfTotalERC1155,
    TotalERC1155FromJSON,
    TotalERC1155FromJSONTyped,
    TotalERC1155ToJSON,
} from './TotalERC1155';
import type { TotalERC20 } from './TotalERC20';
import {
    instanceOfTotalERC20,
    TotalERC20FromJSON,
    TotalERC20FromJSONTyped,
    TotalERC20ToJSON,
} from './TotalERC20';
import type { TotalERC721 } from './TotalERC721';
import {
    instanceOfTotalERC721,
    TotalERC721FromJSON,
    TotalERC721FromJSONTyped,
    TotalERC721ToJSON,
} from './TotalERC721';

/**
 * @type TokenTransferTotal
 * 
 * @export
 */
export type TokenTransferTotal = TotalERC1155 | TotalERC20 | TotalERC721;

export function TokenTransferTotalFromJSON(json: any): TokenTransferTotal {
    return TokenTransferTotalFromJSONTyped(json, false);
}

export function TokenTransferTotalFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenTransferTotal {
    if (json == null) {
        return json;
    }
    return TotalERC1155FromJSONTyped(json, true) || TotalERC20FromJSONTyped(json, true) || TotalERC721FromJSONTyped(json, true);
}

export function TokenTransferTotalToJSON(value?: TokenTransferTotal | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfTotalERC1155(value)) {
        return TotalERC1155ToJSON(value as TotalERC1155);
    }
    if (instanceOfTotalERC20(value)) {
        return TotalERC20ToJSON(value as TotalERC20);
    }
    if (instanceOfTotalERC721(value)) {
        return TotalERC721ToJSON(value as TotalERC721);
    }

    return {};
}

