/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenInfoDetailed
 */
export interface TokenInfoDetailed {
    /**
     * Token Address
     * @type {string}
     * @memberof TokenInfoDetailed
     */
    address: string;
    /**
     * Token circulating market cap
     * @type {string}
     * @memberof TokenInfoDetailed
     */
    circulatingMarketCap: string;
    /**
     * Token decimals
     * @type {string}
     * @memberof TokenInfoDetailed
     */
    decimals: string;
    /**
     * Token exchange rate
     * @type {string}
     * @memberof TokenInfoDetailed
     */
    exchangeRate: string;
    /**
     * Token holders amount
     * @type {string}
     * @memberof TokenInfoDetailed
     */
    holders: string;
    /**
     * Token image URL 
     * @type {string}
     * @memberof TokenInfoDetailed
     */
    iconUrl: string;
    /**
     * Token name
     * @type {string}
     * @memberof TokenInfoDetailed
     */
    name: string;
    /**
     * Token symbol
     * @type {string}
     * @memberof TokenInfoDetailed
     */
    symbol: string;
    /**
     * Token total supply
     * @type {string}
     * @memberof TokenInfoDetailed
     */
    totalSupply: string;
    /**
     * Token type
     * @type {string}
     * @memberof TokenInfoDetailed
     */
    type: string;
    /**
     * Token trading volume for past 24h
     * @type {string}
     * @memberof TokenInfoDetailed
     */
    volume24h: string;
}

/**
 * Check if a given object implements the TokenInfoDetailed interface.
 */
export function instanceOfTokenInfoDetailed(value: object): boolean {
    if (!('address' in value)) return false;
    if (!('circulatingMarketCap' in value)) return false;
    if (!('decimals' in value)) return false;
    if (!('exchangeRate' in value)) return false;
    if (!('holders' in value)) return false;
    if (!('iconUrl' in value)) return false;
    if (!('name' in value)) return false;
    if (!('symbol' in value)) return false;
    if (!('totalSupply' in value)) return false;
    if (!('type' in value)) return false;
    if (!('volume24h' in value)) return false;
    return true;
}

export function TokenInfoDetailedFromJSON(json: any): TokenInfoDetailed {
    return TokenInfoDetailedFromJSONTyped(json, false);
}

export function TokenInfoDetailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenInfoDetailed {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'circulatingMarketCap': json['circulating_market_cap'],
        'decimals': json['decimals'],
        'exchangeRate': json['exchange_rate'],
        'holders': json['holders'],
        'iconUrl': json['icon_url'],
        'name': json['name'],
        'symbol': json['symbol'],
        'totalSupply': json['total_supply'],
        'type': json['type'],
        'volume24h': json['volume_24h'],
    };
}

export function TokenInfoDetailedToJSON(value?: TokenInfoDetailed | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': value['address'],
        'circulating_market_cap': value['circulatingMarketCap'],
        'decimals': value['decimals'],
        'exchange_rate': value['exchangeRate'],
        'holders': value['holders'],
        'icon_url': value['iconUrl'],
        'name': value['name'],
        'symbol': value['symbol'],
        'total_supply': value['totalSupply'],
        'type': value['type'],
        'volume_24h': value['volume24h'],
    };
}

