/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenCounters
 */
export interface TokenCounters {
    /**
     * 
     * @type {string}
     * @memberof TokenCounters
     */
    tokenHoldersCount: string;
    /**
     * 
     * @type {string}
     * @memberof TokenCounters
     */
    transfersCount: string;
}

/**
 * Check if a given object implements the TokenCounters interface.
 */
export function instanceOfTokenCounters(value: object): boolean {
    if (!('tokenHoldersCount' in value)) return false;
    if (!('transfersCount' in value)) return false;
    return true;
}

export function TokenCountersFromJSON(json: any): TokenCounters {
    return TokenCountersFromJSONTyped(json, false);
}

export function TokenCountersFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenCounters {
    if (json == null) {
        return json;
    }
    return {
        
        'tokenHoldersCount': json['token_holders_count'],
        'transfersCount': json['transfers_count'],
    };
}

export function TokenCountersToJSON(value?: TokenCounters | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token_holders_count': value['tokenHoldersCount'],
        'transfers_count': value['transfersCount'],
    };
}

