/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TotalERC1155 } from './TotalERC1155';
import {
    TotalERC1155FromJSON,
    TotalERC1155FromJSONTyped,
    TotalERC1155ToJSON,
} from './TotalERC1155';

/**
 * 
 * @export
 * @interface TotalERC1155Batch
 */
export interface TotalERC1155Batch {
    /**
     * 
     * @type {Array<TotalERC1155>}
     * @memberof TotalERC1155Batch
     */
    items: Array<TotalERC1155>;
}

/**
 * Check if a given object implements the TotalERC1155Batch interface.
 */
export function instanceOfTotalERC1155Batch(value: object): boolean {
    if (!('items' in value)) return false;
    return true;
}

export function TotalERC1155BatchFromJSON(json: any): TotalERC1155Batch {
    return TotalERC1155BatchFromJSONTyped(json, false);
}

export function TotalERC1155BatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): TotalERC1155Batch {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TotalERC1155FromJSON)),
    };
}

export function TotalERC1155BatchToJSON(value?: TotalERC1155Batch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(TotalERC1155ToJSON)),
    };
}

