/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TotalERC1155
 */
export interface TotalERC1155 {
    /**
     * 
     * @type {string}
     * @memberof TotalERC1155
     */
    tokenId: string;
    /**
     * 
     * @type {string}
     * @memberof TotalERC1155
     */
    decimals: string;
    /**
     * 
     * @type {string}
     * @memberof TotalERC1155
     */
    value: string;
}

/**
 * Check if a given object implements the TotalERC1155 interface.
 */
export function instanceOfTotalERC1155(value: object): boolean {
    if (!('tokenId' in value)) return false;
    if (!('decimals' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function TotalERC1155FromJSON(json: any): TotalERC1155 {
    return TotalERC1155FromJSONTyped(json, false);
}

export function TotalERC1155FromJSONTyped(json: any, ignoreDiscriminator: boolean): TotalERC1155 {
    if (json == null) {
        return json;
    }
    return {
        
        'tokenId': json['token_id'],
        'decimals': json['decimals'],
        'value': json['value'],
    };
}

export function TotalERC1155ToJSON(value?: TotalERC1155 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token_id': value['tokenId'],
        'decimals': value['decimals'],
        'value': value['value'],
    };
}

