/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Summary } from './Summary';
import {
    SummaryFromJSON,
    SummaryFromJSONTyped,
    SummaryToJSON,
} from './Summary';

/**
 * 
 * @export
 * @interface TransactionSummaryObj
 */
export interface TransactionSummaryObj {
    /**
     * 
     * @type {Array<Summary>}
     * @memberof TransactionSummaryObj
     */
    summaries?: Array<Summary>;
}

/**
 * Check if a given object implements the TransactionSummaryObj interface.
 */
export function instanceOfTransactionSummaryObj(value: object): boolean {
    return true;
}

export function TransactionSummaryObjFromJSON(json: any): TransactionSummaryObj {
    return TransactionSummaryObjFromJSONTyped(json, false);
}

export function TransactionSummaryObjFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionSummaryObj {
    if (json == null) {
        return json;
    }
    return {
        
        'summaries': json['summaries'] == null ? undefined : ((json['summaries'] as Array<any>).map(SummaryFromJSON)),
    };
}

export function TransactionSummaryObjToJSON(value?: TransactionSummaryObj | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'summaries': value['summaries'] == null ? undefined : ((value['summaries'] as Array<any>).map(SummaryToJSON)),
    };
}

