/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressParam } from './AddressParam';
import {
    AddressParamFromJSON,
    AddressParamFromJSONTyped,
    AddressParamToJSON,
} from './AddressParam';
import type { DecodedInput } from './DecodedInput';
import {
    DecodedInputFromJSON,
    DecodedInputFromJSONTyped,
    DecodedInputToJSON,
} from './DecodedInput';
import type { Fee } from './Fee';
import {
    FeeFromJSON,
    FeeFromJSONTyped,
    FeeToJSON,
} from './Fee';
import type { TokenTransfer } from './TokenTransfer';
import {
    TokenTransferFromJSON,
    TokenTransferFromJSONTyped,
    TokenTransferToJSON,
} from './TokenTransfer';
import type { TransactionAction } from './TransactionAction';
import {
    TransactionActionFromJSON,
    TransactionActionFromJSONTyped,
    TransactionActionToJSON,
} from './TransactionAction';

/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    timestamp: string;
    /**
     * 
     * @type {Fee}
     * @memberof Transaction
     */
    fee: Fee;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    gasLimit: number;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    block: number;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    method: string;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    confirmations: number;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    type: number;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    exchangeRate: string;
    /**
     * 
     * @type {AddressParam}
     * @memberof Transaction
     */
    to: AddressParam;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    txBurntFee: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    maxFeePerGas: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    result: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    hash: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    gasPrice: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    priorityFee: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    baseFeePerGas: string;
    /**
     * 
     * @type {AddressParam}
     * @memberof Transaction
     */
    from: AddressParam;
    /**
     * 
     * @type {Array<TokenTransfer>}
     * @memberof Transaction
     */
    tokenTransfers?: Array<TokenTransfer>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Transaction
     */
    txTypes: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    gasUsed: string;
    /**
     * 
     * @type {AddressParam}
     * @memberof Transaction
     */
    createdContract: AddressParam;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    position: number;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    nonce: number;
    /**
     * 
     * @type {boolean}
     * @memberof Transaction
     */
    hasErrorInInternalTxs: boolean;
    /**
     * 
     * @type {Array<TransactionAction>}
     * @memberof Transaction
     */
    actions: Array<TransactionAction>;
    /**
     * 
     * @type {DecodedInput}
     * @memberof Transaction
     */
    decodedInput: DecodedInput;
    /**
     * 
     * @type {boolean}
     * @memberof Transaction
     */
    tokenTransfersOverflow: boolean;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    rawInput: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    maxPriorityFeePerGas: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    revertReason: string;
    /**
     * 
     * @type {object}
     * @memberof Transaction
     */
    confirmationDuration: object;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    txTag: string;
}

/**
 * Check if a given object implements the Transaction interface.
 */
export function instanceOfTransaction(value: object): boolean {
    if (!('timestamp' in value)) return false;
    if (!('fee' in value)) return false;
    if (!('gasLimit' in value)) return false;
    if (!('block' in value)) return false;
    if (!('status' in value)) return false;
    if (!('method' in value)) return false;
    if (!('confirmations' in value)) return false;
    if (!('type' in value)) return false;
    if (!('exchangeRate' in value)) return false;
    if (!('to' in value)) return false;
    if (!('txBurntFee' in value)) return false;
    if (!('maxFeePerGas' in value)) return false;
    if (!('result' in value)) return false;
    if (!('hash' in value)) return false;
    if (!('gasPrice' in value)) return false;
    if (!('priorityFee' in value)) return false;
    if (!('baseFeePerGas' in value)) return false;
    if (!('from' in value)) return false;
    if (!('txTypes' in value)) return false;
    if (!('gasUsed' in value)) return false;
    if (!('createdContract' in value)) return false;
    if (!('position' in value)) return false;
    if (!('nonce' in value)) return false;
    if (!('hasErrorInInternalTxs' in value)) return false;
    if (!('actions' in value)) return false;
    if (!('decodedInput' in value)) return false;
    if (!('tokenTransfersOverflow' in value)) return false;
    if (!('rawInput' in value)) return false;
    if (!('value' in value)) return false;
    if (!('maxPriorityFeePerGas' in value)) return false;
    if (!('revertReason' in value)) return false;
    if (!('confirmationDuration' in value)) return false;
    if (!('txTag' in value)) return false;
    return true;
}

export function TransactionFromJSON(json: any): Transaction {
    return TransactionFromJSONTyped(json, false);
}

export function TransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transaction {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'fee': FeeFromJSON(json['fee']),
        'gasLimit': json['gas_limit'],
        'block': json['block'],
        'status': json['status'],
        'method': json['method'],
        'confirmations': json['confirmations'],
        'type': json['type'],
        'exchangeRate': json['exchange_rate'],
        'to': AddressParamFromJSON(json['to']),
        'txBurntFee': json['tx_burnt_fee'],
        'maxFeePerGas': json['max_fee_per_gas'],
        'result': json['result'],
        'hash': json['hash'],
        'gasPrice': json['gas_price'],
        'priorityFee': json['priority_fee'],
        'baseFeePerGas': json['base_fee_per_gas'],
        'from': AddressParamFromJSON(json['from']),
        'tokenTransfers': json['token_transfers'] == null ? undefined : ((json['token_transfers'] as Array<any>).map(TokenTransferFromJSON)),
        'txTypes': json['tx_types'],
        'gasUsed': json['gas_used'],
        'createdContract': AddressParamFromJSON(json['created_contract']),
        'position': json['position'],
        'nonce': json['nonce'],
        'hasErrorInInternalTxs': json['has_error_in_internal_txs'],
        'actions': ((json['actions'] as Array<any>).map(TransactionActionFromJSON)),
        'decodedInput': DecodedInputFromJSON(json['decoded_input']),
        'tokenTransfersOverflow': json['token_transfers_overflow'],
        'rawInput': json['raw_input'],
        'value': json['value'],
        'maxPriorityFeePerGas': json['max_priority_fee_per_gas'],
        'revertReason': json['revert_reason'],
        'confirmationDuration': json['confirmation_duration'],
        'txTag': json['tx_tag'],
    };
}

export function TransactionToJSON(value?: Transaction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'timestamp': value['timestamp'],
        'fee': FeeToJSON(value['fee']),
        'gas_limit': value['gasLimit'],
        'block': value['block'],
        'status': value['status'],
        'method': value['method'],
        'confirmations': value['confirmations'],
        'type': value['type'],
        'exchange_rate': value['exchangeRate'],
        'to': AddressParamToJSON(value['to']),
        'tx_burnt_fee': value['txBurntFee'],
        'max_fee_per_gas': value['maxFeePerGas'],
        'result': value['result'],
        'hash': value['hash'],
        'gas_price': value['gasPrice'],
        'priority_fee': value['priorityFee'],
        'base_fee_per_gas': value['baseFeePerGas'],
        'from': AddressParamToJSON(value['from']),
        'token_transfers': value['tokenTransfers'] == null ? undefined : ((value['tokenTransfers'] as Array<any>).map(TokenTransferToJSON)),
        'tx_types': value['txTypes'],
        'gas_used': value['gasUsed'],
        'created_contract': AddressParamToJSON(value['createdContract']),
        'position': value['position'],
        'nonce': value['nonce'],
        'has_error_in_internal_txs': value['hasErrorInInternalTxs'],
        'actions': ((value['actions'] as Array<any>).map(TransactionActionToJSON)),
        'decoded_input': DecodedInputToJSON(value['decodedInput']),
        'token_transfers_overflow': value['tokenTransfersOverflow'],
        'raw_input': value['rawInput'],
        'value': value['value'],
        'max_priority_fee_per_gas': value['maxPriorityFeePerGas'],
        'revert_reason': value['revertReason'],
        'confirmation_duration': value['confirmationDuration'],
        'tx_tag': value['txTag'],
    };
}

