/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionActionAaveV3LiquidationCall
 */
export interface TransactionActionAaveV3LiquidationCall {
    /**
     * 
     * @type {object}
     * @memberof TransactionActionAaveV3LiquidationCall
     */
    data: object;
    /**
     * 
     * @type {string}
     * @memberof TransactionActionAaveV3LiquidationCall
     */
    protocol: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionActionAaveV3LiquidationCall
     */
    type: string;
}

/**
 * Check if a given object implements the TransactionActionAaveV3LiquidationCall interface.
 */
export function instanceOfTransactionActionAaveV3LiquidationCall(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('protocol' in value)) return false;
    if (!('type' in value)) return false;
    return true;
}

export function TransactionActionAaveV3LiquidationCallFromJSON(json: any): TransactionActionAaveV3LiquidationCall {
    return TransactionActionAaveV3LiquidationCallFromJSONTyped(json, false);
}

export function TransactionActionAaveV3LiquidationCallFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionActionAaveV3LiquidationCall {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'protocol': json['protocol'],
        'type': json['type'],
    };
}

export function TransactionActionAaveV3LiquidationCallToJSON(value?: TransactionActionAaveV3LiquidationCall | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'],
        'protocol': value['protocol'],
        'type': value['type'],
    };
}

