/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionActionUniswapV3MintNFT
 */
export interface TransactionActionUniswapV3MintNFT {
    /**
     * 
     * @type {object}
     * @memberof TransactionActionUniswapV3MintNFT
     */
    data: object;
    /**
     * 
     * @type {string}
     * @memberof TransactionActionUniswapV3MintNFT
     */
    protocol: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionActionUniswapV3MintNFT
     */
    type: string;
}

/**
 * Check if a given object implements the TransactionActionUniswapV3MintNFT interface.
 */
export function instanceOfTransactionActionUniswapV3MintNFT(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('protocol' in value)) return false;
    if (!('type' in value)) return false;
    return true;
}

export function TransactionActionUniswapV3MintNFTFromJSON(json: any): TransactionActionUniswapV3MintNFT {
    return TransactionActionUniswapV3MintNFTFromJSONTyped(json, false);
}

export function TransactionActionUniswapV3MintNFTFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionActionUniswapV3MintNFT {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'protocol': json['protocol'],
        'type': json['type'],
    };
}

export function TransactionActionUniswapV3MintNFTToJSON(value?: TransactionActionUniswapV3MintNFT | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'],
        'protocol': value['protocol'],
        'type': value['type'],
    };
}

