/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionChartItem
 */
export interface TransactionChartItem {
    /**
     * 
     * @type {string}
     * @memberof TransactionChartItem
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionChartItem
     */
    txCount: number;
}

/**
 * Check if a given object implements the TransactionChartItem interface.
 */
export function instanceOfTransactionChartItem(value: object): boolean {
    if (!('date' in value)) return false;
    if (!('txCount' in value)) return false;
    return true;
}

export function TransactionChartItemFromJSON(json: any): TransactionChartItem {
    return TransactionChartItemFromJSONTyped(json, false);
}

export function TransactionChartItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionChartItem {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'txCount': json['tx_count'],
    };
}

export function TransactionChartItemToJSON(value?: TransactionChartItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'date': value['date'],
        'tx_count': value['txCount'],
    };
}

