/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TransactionActionAaveV3BSWRF } from './TransactionActionAaveV3BSWRF';
import {
    instanceOfTransactionActionAaveV3BSWRF,
    TransactionActionAaveV3BSWRFFromJSON,
    TransactionActionAaveV3BSWRFFromJSONTyped,
    TransactionActionAaveV3BSWRFToJSON,
} from './TransactionActionAaveV3BSWRF';
import type { TransactionActionAaveV3EnableDisableCollateral } from './TransactionActionAaveV3EnableDisableCollateral';
import {
    instanceOfTransactionActionAaveV3EnableDisableCollateral,
    TransactionActionAaveV3EnableDisableCollateralFromJSON,
    TransactionActionAaveV3EnableDisableCollateralFromJSONTyped,
    TransactionActionAaveV3EnableDisableCollateralToJSON,
} from './TransactionActionAaveV3EnableDisableCollateral';
import type { TransactionActionAaveV3LiquidationCall } from './TransactionActionAaveV3LiquidationCall';
import {
    instanceOfTransactionActionAaveV3LiquidationCall,
    TransactionActionAaveV3LiquidationCallFromJSON,
    TransactionActionAaveV3LiquidationCallFromJSONTyped,
    TransactionActionAaveV3LiquidationCallToJSON,
} from './TransactionActionAaveV3LiquidationCall';
import type { TransactionActionUniswapV3BCS } from './TransactionActionUniswapV3BCS';
import {
    instanceOfTransactionActionUniswapV3BCS,
    TransactionActionUniswapV3BCSFromJSON,
    TransactionActionUniswapV3BCSFromJSONTyped,
    TransactionActionUniswapV3BCSToJSON,
} from './TransactionActionUniswapV3BCS';
import type { TransactionActionUniswapV3MintNFT } from './TransactionActionUniswapV3MintNFT';
import {
    instanceOfTransactionActionUniswapV3MintNFT,
    TransactionActionUniswapV3MintNFTFromJSON,
    TransactionActionUniswapV3MintNFTFromJSONTyped,
    TransactionActionUniswapV3MintNFTToJSON,
} from './TransactionActionUniswapV3MintNFT';

/**
 * @type TransactionAction
 * 
 * @export
 */
export type TransactionAction = TransactionActionAaveV3BSWRF | TransactionActionAaveV3EnableDisableCollateral | TransactionActionAaveV3LiquidationCall | TransactionActionUniswapV3BCS | TransactionActionUniswapV3MintNFT;

export function TransactionActionFromJSON(json: any): TransactionAction {
    return TransactionActionFromJSONTyped(json, false);
}

export function TransactionActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionAction {
    if (json == null) {
        return json;
    }
    return TransactionActionAaveV3BSWRFFromJSONTyped(json, true) || TransactionActionAaveV3EnableDisableCollateralFromJSONTyped(json, true) || TransactionActionAaveV3LiquidationCallFromJSONTyped(json, true) || TransactionActionUniswapV3BCSFromJSONTyped(json, true) || TransactionActionUniswapV3MintNFTFromJSONTyped(json, true);
}

export function TransactionActionToJSON(value?: TransactionAction | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfTransactionActionAaveV3BSWRF(value)) {
        return TransactionActionAaveV3BSWRFToJSON(value as TransactionActionAaveV3BSWRF);
    }
    if (instanceOfTransactionActionAaveV3EnableDisableCollateral(value)) {
        return TransactionActionAaveV3EnableDisableCollateralToJSON(value as TransactionActionAaveV3EnableDisableCollateral);
    }
    if (instanceOfTransactionActionAaveV3LiquidationCall(value)) {
        return TransactionActionAaveV3LiquidationCallToJSON(value as TransactionActionAaveV3LiquidationCall);
    }
    if (instanceOfTransactionActionUniswapV3BCS(value)) {
        return TransactionActionUniswapV3BCSToJSON(value as TransactionActionUniswapV3BCS);
    }
    if (instanceOfTransactionActionUniswapV3MintNFT(value)) {
        return TransactionActionUniswapV3MintNFTToJSON(value as TransactionActionUniswapV3MintNFT);
    }

    return {};
}

