/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CelestiaBlob
 */
export interface V1CelestiaBlob {
    /**
     * 
     * @type {string}
     * @memberof V1CelestiaBlob
     */
    height?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CelestiaBlob
     */
    namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CelestiaBlob
     */
    commitment?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CelestiaBlob
     */
    timestamp?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CelestiaBlob
     */
    size?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CelestiaBlob
     */
    data?: string;
}

/**
 * Check if a given object implements the V1CelestiaBlob interface.
 */
export function instanceOfV1CelestiaBlob(value: object): boolean {
    return true;
}

export function V1CelestiaBlobFromJSON(json: any): V1CelestiaBlob {
    return V1CelestiaBlobFromJSONTyped(json, false);
}

export function V1CelestiaBlobFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CelestiaBlob {
    if (json == null) {
        return json;
    }
    return {
        
        'height': json['height'] == null ? undefined : json['height'],
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
        'commitment': json['commitment'] == null ? undefined : json['commitment'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'size': json['size'] == null ? undefined : json['size'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function V1CelestiaBlobToJSON(value?: V1CelestiaBlob | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'height': value['height'],
        'namespace': value['namespace'],
        'commitment': value['commitment'],
        'timestamp': value['timestamp'],
        'size': value['size'],
        'data': value['data'],
    };
}

