/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CelestiaBlobId
 */
export interface V1CelestiaBlobId {
    /**
     * 
     * @type {string}
     * @memberof V1CelestiaBlobId
     */
    height?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CelestiaBlobId
     */
    namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CelestiaBlobId
     */
    commitment?: string;
}

/**
 * Check if a given object implements the V1CelestiaBlobId interface.
 */
export function instanceOfV1CelestiaBlobId(value: object): boolean {
    return true;
}

export function V1CelestiaBlobIdFromJSON(json: any): V1CelestiaBlobId {
    return V1CelestiaBlobIdFromJSONTyped(json, false);
}

export function V1CelestiaBlobIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CelestiaBlobId {
    if (json == null) {
        return json;
    }
    return {
        
        'height': json['height'] == null ? undefined : json['height'],
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
        'commitment': json['commitment'] == null ? undefined : json['commitment'],
    };
}

export function V1CelestiaBlobIdToJSON(value?: V1CelestiaBlobId | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'height': value['height'],
        'namespace': value['namespace'],
        'commitment': value['commitment'],
    };
}

