/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HealthCheckResponseServingStatus } from './HealthCheckResponseServingStatus';
import {
    HealthCheckResponseServingStatusFromJSON,
    HealthCheckResponseServingStatusFromJSONTyped,
    HealthCheckResponseServingStatusToJSON,
} from './HealthCheckResponseServingStatus';

/**
 * 
 * @export
 * @interface V1HealthCheckResponse
 */
export interface V1HealthCheckResponse {
    /**
     * 
     * @type {HealthCheckResponseServingStatus}
     * @memberof V1HealthCheckResponse
     */
    status?: HealthCheckResponseServingStatus;
}

/**
 * Check if a given object implements the V1HealthCheckResponse interface.
 */
export function instanceOfV1HealthCheckResponse(value: object): boolean {
    return true;
}

export function V1HealthCheckResponseFromJSON(json: any): V1HealthCheckResponse {
    return V1HealthCheckResponseFromJSONTyped(json, false);
}

export function V1HealthCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1HealthCheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : HealthCheckResponseServingStatusFromJSON(json['status']),
    };
}

export function V1HealthCheckResponseToJSON(value?: V1HealthCheckResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': HealthCheckResponseServingStatusToJSON(value['status']),
    };
}

