/* tslint:disable */
/* eslint-disable */
/**
 * BlockScout API
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressParam } from './AddressParam';
import {
    AddressParamFromJSON,
    AddressParamFromJSONTyped,
    AddressParamToJSON,
} from './AddressParam';

/**
 * 
 * @export
 * @interface Withdrawal
 */
export interface Withdrawal {
    /**
     * 
     * @type {number}
     * @memberof Withdrawal
     */
    index: number;
    /**
     * 
     * @type {string}
     * @memberof Withdrawal
     */
    amount: string;
    /**
     * 
     * @type {number}
     * @memberof Withdrawal
     */
    validatorIndex: number;
    /**
     * 
     * @type {AddressParam}
     * @memberof Withdrawal
     */
    receiver?: AddressParam;
    /**
     * 
     * @type {number}
     * @memberof Withdrawal
     */
    blockNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof Withdrawal
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the Withdrawal interface.
 */
export function instanceOfWithdrawal(value: object): boolean {
    if (!('index' in value)) return false;
    if (!('amount' in value)) return false;
    if (!('validatorIndex' in value)) return false;
    return true;
}

export function WithdrawalFromJSON(json: any): Withdrawal {
    return WithdrawalFromJSONTyped(json, false);
}

export function WithdrawalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Withdrawal {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'amount': json['amount'],
        'validatorIndex': json['validator_index'],
        'receiver': json['receiver'] == null ? undefined : AddressParamFromJSON(json['receiver']),
        'blockNumber': json['block_number'] == null ? undefined : json['block_number'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function WithdrawalToJSON(value?: Withdrawal | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'index': value['index'],
        'amount': value['amount'],
        'validator_index': value['validatorIndex'],
        'receiver': AddressParamToJSON(value['receiver']),
        'block_number': value['blockNumber'],
        'timestamp': value['timestamp'],
    };
}

